# Generated by Django 4.2.4 on 2024-10-17 09:57

import uuid

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iteration_manager", "0022_iteration_serial_id"),
        ("site_manager", "0017_site_deleted_at_site_is_deleted"),
        ("shared", "0026_batchjob_deleted_at_batchjob_is_deleted"),
        ("org_manager", "0009_rename_features_organisation_feature_flags"),
        ("gis", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultPresets",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("value", models.JSONField()),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GCP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.TextField()),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("controlpoint", "CONTROLPOINT"),
                            ("checkpoint", "CHECKPOINT"),
                        ],
                        default="controlpoint",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326),
                ),
                (
                    "location_wgs84",
                    django.contrib.gis.db.models.fields.PointField(
                        dim=3, null=True, srid=4326
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeotagImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326),
                ),
                (
                    "location_wgs84",
                    django.contrib.gis.db.models.fields.PointField(
                        dim=3, null=True, srid=4326
                    ),
                ),
                ("filename", models.TextField()),
                ("is_image_available", models.BooleanField(default=False)),
                ("is_geotag_disabled", models.BooleanField(default=False)),
                ("is_image_disabled", models.BooleanField(default=False)),
                (
                    "x_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "y_accuracy",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=6),
                ),
                (
                    "horizontal_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "vertical_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "omega",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "omega_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "phi",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "phi_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "kappa",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "kappa_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "yaw",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "yaw_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "pitch",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "pitch_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "roll",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "roll_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "image_orientation",
                    models.TextField(
                        choices=[
                            ("horizontal_normal", "HORIZONTAL_NORMAL"),
                            ("mirrored_horizontal", "MIRRORED_HORIZONTAL"),
                            ("rotated_180", "ROTATED_180"),
                            ("mirrored_vertical", "MIRRORED_VERTICAL"),
                            (
                                "mirrored_horizontal_then_rotated_90_ccw",
                                "MIRRORED_HORIZONTAL_THEN_ROTATED_90_CCW",
                            ),
                            ("rotated_90_cw", "ROTATED_90_CW"),
                            (
                                "mirrored_horizontal_then_rotated_90_cw",
                                "MIRRORED_HORIZONTAL_THEN_ROTATED_90_CW",
                            ),
                            ("rotated_90_ccw", "ROTATED_90_CCW"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MergedDataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("serial_id", models.TextField(blank=True, editable=False, null=True)),
                ("name", models.TextField()),
                ("number_of_photos", models.IntegerField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("is_align_before_merge", models.BooleanField(default=False)),
                (
                    "alignment_method",
                    models.TextField(
                        choices=[
                            ("point_based", "POINT_BASED"),
                            ("marker_based", "MARKER_BASED"),
                            ("camera_based", "CAMERA_BASED"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                ("is_marker_present", models.BooleanField(default=False)),
                ("are_geotags_present", models.BooleanField(default=False)),
                ("is_preparing_gcp", models.BooleanField(default=False)),
                ("is_gcp_present", models.BooleanField(default=False)),
                ("is_gcp_tagged", models.BooleanField(default=False)),
                ("is_sparse_point_cloud_merged", models.BooleanField(default=False)),
                ("is_dense_point_cloud_merged", models.BooleanField(default=False)),
                ("is_dem_merged", models.BooleanField(default=False)),
                ("is_ortho_merged", models.BooleanField(default=False)),
                ("is_sparse_point_cloud_present", models.BooleanField(default=False)),
                ("is_dense_point_cloud_present", models.BooleanField(default=False)),
                ("is_dem_present", models.BooleanField(default=False)),
                ("is_ortho_present", models.BooleanField(default=False)),
                ("is_report_present", models.BooleanField(default=False)),
                (
                    "geotag_vertical_crs",
                    models.TextField(
                        choices=[
                            ("Ellipsoidal", "ELLIPSOIDAL"),
                            ("EGM96", "EGM96"),
                            ("EGM2008", "EGM2008"),
                        ]
                    ),
                ),
                (
                    "geotag_rotation_angle_type",
                    models.TextField(
                        choices=[
                            ("omega_phi_kappa", "OMEGA_PHI_KAPPA"),
                            ("yaw_pitch_roll", "YAW_PITCH_ROLL"),
                        ],
                        default="omega_phi_kappa",
                    ),
                ),
                (
                    "geotag_column_order",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                (
                    "gcp_vertical_crs",
                    models.TextField(
                        choices=[
                            ("Ellipsoidal", "ELLIPSOIDAL"),
                            ("EGM96", "EGM96"),
                            ("EGM2008", "EGM2008"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "merging_status",
                    models.TextField(
                        choices=[
                            ("cancelled", "CANCELLED"),
                            ("completed", "COMPLETED"),
                            ("error", "ERROR"),
                            ("pending", "PENDING"),
                            ("processing", "PROCESSING"),
                        ],
                        default="pending",
                    ),
                ),
                (
                    "batch_job_details",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shared.batchjob",
                    ),
                ),
                (
                    "gcp_horizontal_crs",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gis.postgisspatialrefsys",
                    ),
                ),
                (
                    "geotag_horizontal_crs",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gis.postgisspatialrefsys",
                    ),
                ),
                (
                    "input_image_s3_folder_info",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="input_image_s3_folder_merged_dataset",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "output_dem_file_info",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="output_dem_file_merged_dataset",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "output_dense_point_cloud_file_info",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="output_dense_point_cloud_file_merged_dataset",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "output_ortho_file_info",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="output_ortho_file_merged_dataset",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "output_psx_file_info",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="output_psx_file_merged_dataset",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "output_report_file_info",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="output_report_file_merged_dataset",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_manager.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProcessingIterationData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "geotag_column_order",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), null=True, size=None
                    ),
                ),
                ("have_geotags", models.BooleanField(default=False)),
                ("have_gcps", models.BooleanField(default=False)),
                ("is_gcp_tagged", models.BooleanField(default=False)),
                (
                    "geotag_vertical_crs",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("Ellipsoidal", "ELLIPSOIDAL"),
                            ("EGM96", "EGM96"),
                            ("EGM2008", "EGM2008"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "gcp_vertical_crs",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("Ellipsoidal", "ELLIPSOIDAL"),
                            ("EGM96", "EGM96"),
                            ("EGM2008", "EGM2008"),
                        ],
                        null=True,
                    ),
                ),
                ("is_preparing_geotags", models.BooleanField(default=False)),
                (
                    "rotation_angle_type",
                    models.TextField(
                        choices=[
                            ("omega_phi_kappa", "OMEGA_PHI_KAPPA"),
                            ("yaw_pitch_roll", "YAW_PITCH_ROLL"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "number_of_images",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "number_of_images_enabled",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "exif_extractor_job_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shared.batchjob",
                    ),
                ),
                (
                    "gcp_horizontal_crs",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gis.postgisspatialrefsys",
                    ),
                ),
                (
                    "geotag_horizontal_crs",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gis.postgisspatialrefsys",
                    ),
                ),
                (
                    "image_folder_path",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="processing_iteration_image_folder_path",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "iteration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="processing_data",
                        to="iteration_manager.iteration",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "serial_id",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("name", models.TextField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("cancelled", "CANCELLED"),
                            ("completed", "COMPLETED"),
                            ("error", "ERROR"),
                            ("pending", "PENDING"),
                            ("processing", "PROCESSING"),
                        ],
                        default="pending",
                    ),
                ),
                ("options", models.JSONField(null=True)),
                ("preset_id", models.CharField(max_length=255, null=True)),
                (
                    "x_average_error",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "y_average_error",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "z_average_error",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "end_stage",
                    models.TextField(
                        choices=[
                            ("align-photos", "ALIGN_PHOTOS"),
                            ("generate-point-cloud", "GENERATE_POINT_CLOUD"),
                            ("generate-orthomosaic", "GENERATE_ORTHOMOSAIC"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "continued_from",
                    models.TextField(
                        choices=[
                            ("task", "TASK"),
                            ("parent_iteration", "PARENT_ITERATION"),
                            (
                                "parent_merged_dataset_input",
                                "PARENT_MERGED_DATASET_INPUT",
                            ),
                            (
                                "parent_merged_dataset_output",
                                "PARENT_MERGED_DATASET_OUTPUT",
                            ),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                ("is_sparse_point_cloud_present", models.BooleanField(default=False)),
                ("is_dense_point_cloud_present", models.BooleanField(default=False)),
                ("is_dem_present", models.BooleanField(default=False)),
                ("is_ortho_present", models.BooleanField(default=False)),
                (
                    "rotation_angle_type",
                    models.TextField(
                        choices=[
                            ("omega_phi_kappa", "OMEGA_PHI_KAPPA"),
                            ("yaw_pitch_roll", "YAW_PITCH_ROLL"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "clipping_boundary",
                    django.contrib.gis.db.models.fields.GeometryCollectionField(
                        dim=3, null=True, srid=4326
                    ),
                ),
                (
                    "input_geotag_vertical_crs",
                    models.TextField(
                        choices=[
                            ("Ellipsoidal", "ELLIPSOIDAL"),
                            ("EGM96", "EGM96"),
                            ("EGM2008", "EGM2008"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "input_gcp_vertical_crs",
                    models.TextField(
                        choices=[
                            ("Ellipsoidal", "ELLIPSOIDAL"),
                            ("EGM96", "EGM96"),
                            ("EGM2008", "EGM2008"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "output_vertical_crs",
                    models.TextField(
                        choices=[
                            ("Ellipsoidal", "ELLIPSOIDAL"),
                            ("EGM96", "EGM96"),
                            ("EGM2008", "EGM2008"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "cropping_region",
                    django.contrib.gis.db.models.fields.GeometryCollectionField(
                        dim=3, null=True, srid=4326
                    ),
                ),
                (
                    "cropping_region_behaviour",
                    models.TextField(
                        choices=[("exclude", "EXCLUDE"), ("include", "INCLUDE")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "batch_job_details",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="task_batch_job",
                        to="shared.batchjob",
                    ),
                ),
                (
                    "continued_from_task",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="processing_workflow_manager.task",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "input_gcp_horizontal_crs",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gis.postgisspatialrefsys",
                    ),
                ),
                (
                    "input_geotag_horizontal_crs",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gis.postgisspatialrefsys",
                    ),
                ),
                (
                    "iteration_data",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing_workflow_manager.processingiterationdata",
                    ),
                ),
                (
                    "merged_dataset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing_workflow_manager.mergeddataset",
                    ),
                ),
                (
                    "output_all_assets_zip",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="output_all_assets_zip_task",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "output_dem",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="output_dem_task",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "output_dem_cog",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="output_dem_cog_task",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "output_dense_point_cloud_file_info",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="output_dense_point_cloud_file_task",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "output_folder_path",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="output_folder_task",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "output_horizontal_crs",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="gis.postgisspatialrefsys",
                    ),
                ),
                (
                    "output_ortho",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="output_ortho_task",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "output_ortho_cog",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="output_ortho_cog_task",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "output_ortho_tile_zip",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="putput_ortho_tile_zip_task",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "output_project_file_info",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="output_project_file_task",
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "output_report",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="output_report_task",
                        to="shared.fileinfo",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskGCP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.TextField(blank=True)),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("controlpoint", "CONTROLPOINT"),
                            ("checkpoint", "CHECKPOINT"),
                        ],
                        default="controlpoint",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326),
                ),
                (
                    "location_wgs84",
                    django.contrib.gis.db.models.fields.PointField(
                        dim=3, null=True, srid=4326
                    ),
                ),
                (
                    "gcp",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="processing_workflow_manager.gcp",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing_workflow_manager.task",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskGeotagImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326),
                ),
                (
                    "location_wgs84",
                    django.contrib.gis.db.models.fields.PointField(
                        dim=3, null=True, srid=4326
                    ),
                ),
                ("filename", models.TextField()),
                ("is_image_available", models.BooleanField(default=False)),
                ("is_geotag_disabled", models.BooleanField(default=False)),
                ("is_image_disabled", models.BooleanField(default=False)),
                (
                    "x_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "y_accuracy",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=6),
                ),
                (
                    "horizontal_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "vertical_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "omega",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "omega_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "phi",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "phi_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "kappa",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "kappa_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "yaw",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "yaw_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "pitch",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "pitch_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "roll",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "roll_accuracy",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "norm_error",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "error_x",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "error_y",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "error_z",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "image_orientation",
                    models.TextField(
                        choices=[
                            ("horizontal_normal", "HORIZONTAL_NORMAL"),
                            ("mirrored_horizontal", "MIRRORED_HORIZONTAL"),
                            ("rotated_180", "ROTATED_180"),
                            ("mirrored_vertical", "MIRRORED_VERTICAL"),
                            (
                                "mirrored_horizontal_then_rotated_90_ccw",
                                "MIRRORED_HORIZONTAL_THEN_ROTATED_90_CCW",
                            ),
                            ("rotated_90_cw", "ROTATED_90_CW"),
                            (
                                "mirrored_horizontal_then_rotated_90_cw",
                                "MIRRORED_HORIZONTAL_THEN_ROTATED_90_CW",
                            ),
                            ("rotated_90_ccw", "ROTATED_90_CCW"),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "geotag_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="processing_workflow_manager.geotagimage",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing_workflow_manager.task",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaskGCPImageTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_x", models.DecimalField(decimal_places=2, max_digits=6)),
                ("image_y", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "task_gcp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing_workflow_manager.taskgcp",
                    ),
                ),
                (
                    "task_geotag_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing_workflow_manager.taskgeotagimage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrgPresets",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                ("value", models.JSONField()),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="org_manager.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MergedDatasetInputDataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "input_dataset_type",
                    models.TextField(
                        choices=[
                            ("iteration", "ITERATION"),
                            ("merged_dataset", "MERGED_DATASET"),
                            ("task", "TASK"),
                        ]
                    ),
                ),
                (
                    "input_iteration_data",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing_workflow_manager.processingiterationdata",
                    ),
                ),
                (
                    "input_merged_dataset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing_workflow_manager.mergeddataset",
                    ),
                ),
                (
                    "input_task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing_workflow_manager.task",
                    ),
                ),
                (
                    "output_merged_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_dataset",
                        to="processing_workflow_manager.mergeddataset",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="geotagimage",
            name="iteration_data",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="processing_workflow_manager.processingiterationdata",
            ),
        ),
        migrations.AddField(
            model_name="geotagimage",
            name="merged_dataset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="processing_workflow_manager.mergeddataset",
            ),
        ),
        migrations.CreateModel(
            name="GCPImageTags",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_x", models.DecimalField(decimal_places=2, max_digits=6)),
                ("image_y", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "gcp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing_workflow_manager.gcp",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing_workflow_manager.geotagimage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gcp",
            name="iteration_data",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="processing_workflow_manager.processingiterationdata",
            ),
        ),
        migrations.AddField(
            model_name="gcp",
            name="merged_dataset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="processing_workflow_manager.mergeddataset",
            ),
        ),
        migrations.CreateModel(
            name="ApproxGCPImageTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_x", models.DecimalField(decimal_places=2, max_digits=6)),
                ("image_y", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "gcp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing_workflow_manager.gcp",
                    ),
                ),
                (
                    "geotag_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing_workflow_manager.geotagimage",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="taskgcpimagetag",
            constraint=models.UniqueConstraint(
                fields=("task_gcp_id", "task_geotag_image_id"),
                name="unique_task_gcp_image_tags",
            ),
        ),
        migrations.AddConstraint(
            model_name="mergeddatasetinputdataset",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("input_dataset_type", "iteration"),
                        ("input_iteration_data__isnull", False),
                    ),
                    models.Q(
                        ("input_dataset_type", "task"), ("input_task__isnull", False)
                    ),
                    models.Q(
                        ("input_dataset_type", "merged_dataset"),
                        ("input_merged_dataset__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="check_task_or_iteration_or_merged_dataset",
            ),
        ),
        migrations.AddConstraint(
            model_name="mergeddataset",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_align_before_merge", False),
                    models.Q(
                        ("alignment_method__isnull", False),
                        ("is_align_before_merge", True),
                    ),
                    _connector="OR",
                ),
                name="check_alignment_method_if_align_before_merge",
            ),
        ),
        migrations.AddConstraint(
            model_name="geotagimage",
            constraint=models.UniqueConstraint(
                fields=("iteration_data_id", "merged_dataset_id", "filename"),
                name="unique_geotag",
            ),
        ),
        migrations.AddConstraint(
            model_name="geotagimage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("iteration_data__isnull", False),
                    ("merged_dataset__isnull", False),
                    _connector="OR",
                ),
                name="iteration_or_merged_dataset_required_geotag_image",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gcpimagetags",
            unique_together={("gcp", "image")},
        ),
        migrations.AddConstraint(
            model_name="gcp",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("iteration_data__isnull", False),
                    ("merged_dataset__isnull", False),
                    _connector="OR",
                ),
                name="iteration_or_merged_dataset_required_gcp",
            ),
        ),
    ]
