# Generated by Django 4.2.4 on 2024-10-23 12:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processing_workflow_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geotagimage",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=None, dim=3, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="geotagimage",
            name="y_accuracy",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="taskgeotagimage",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=None, dim=3, null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="taskgeotagimage",
            name="y_accuracy",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
    ]
