# Generated by Django 4.2.4 on 2024-11-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "processing_workflow_manager",
            "0003_remove_gcp_iteration_or_merged_dataset_required_gcp_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gcp",
            name="location",
        ),
        migrations.AddField(
            model_name="gcp",
            name="x_coordinate",
            field=models.DecimalField(decimal_places=10, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name="gcp",
            name="y_coordinate",
            field=models.DecimalField(decimal_places=10, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name="gcp",
            name="z_coordinate",
            field=models.DecimalField(decimal_places=10, max_digits=17, null=True),
        ),
    ]
