# Generated by Django 4.2.4 on 2024-11-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "processing_workflow_manager",
            "0004_remove_gcp_location_gcp_x_coordinate_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="mergeddataset",
            old_name="is_gcp_present",
            new_name="are_gcps_present",
        ),
        migrations.RenameField(
            model_name="processingiterationdata",
            old_name="have_gcps",
            new_name="are_gcps_present",
        ),
        migrations.RenameField(
            model_name="processingiterationdata",
            old_name="have_geotags",
            new_name="are_geotags_present",
        ),
        migrations.RemoveField(
            model_name="taskgcp",
            name="location",
        ),
        migrations.RemoveField(
            model_name="taskgeotagimage",
            name="location",
        ),
        migrations.AddField(
            model_name="taskgcp",
            name="x_coordinate",
            field=models.DecimalField(decimal_places=10, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name="taskgcp",
            name="y_coordinate",
            field=models.DecimalField(decimal_places=10, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name="taskgcp",
            name="z_coordinate",
            field=models.DecimalField(decimal_places=10, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name="taskgeotagimage",
            name="x_coordinate",
            field=models.DecimalField(decimal_places=10, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name="taskgeotagimage",
            name="y_coordinate",
            field=models.DecimalField(decimal_places=10, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name="taskgeotagimage",
            name="z_coordinate",
            field=models.DecimalField(decimal_places=10, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name="mergeddataset",
            name="gcp_vertical_crs",
            field=models.TextField(
                choices=[
                    ("Ellipsoidal", "ELLIPSOIDAL"),
                    ("EGM96", "EGM96"),
                    ("EGM2008", "EGM2008"),
                    ("AHD71", "AHD71"),
                    ("CGVD2013", "CGVD2013"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mergeddataset",
            name="geotag_vertical_crs",
            field=models.TextField(
                choices=[
                    ("Ellipsoidal", "ELLIPSOIDAL"),
                    ("EGM96", "EGM96"),
                    ("EGM2008", "EGM2008"),
                    ("AHD71", "AHD71"),
                    ("CGVD2013", "CGVD2013"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="processingiterationdata",
            name="gcp_vertical_crs",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Ellipsoidal", "ELLIPSOIDAL"),
                    ("EGM96", "EGM96"),
                    ("EGM2008", "EGM2008"),
                    ("AHD71", "AHD71"),
                    ("CGVD2013", "CGVD2013"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="processingiterationdata",
            name="geotag_vertical_crs",
            field=models.TextField(
                blank=True,
                choices=[
                    ("Ellipsoidal", "ELLIPSOIDAL"),
                    ("EGM96", "EGM96"),
                    ("EGM2008", "EGM2008"),
                    ("AHD71", "AHD71"),
                    ("CGVD2013", "CGVD2013"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="input_gcp_vertical_crs",
            field=models.TextField(
                choices=[
                    ("Ellipsoidal", "ELLIPSOIDAL"),
                    ("EGM96", "EGM96"),
                    ("EGM2008", "EGM2008"),
                    ("AHD71", "AHD71"),
                    ("CGVD2013", "CGVD2013"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="input_geotag_vertical_crs",
            field=models.TextField(
                choices=[
                    ("Ellipsoidal", "ELLIPSOIDAL"),
                    ("EGM96", "EGM96"),
                    ("EGM2008", "EGM2008"),
                    ("AHD71", "AHD71"),
                    ("CGVD2013", "CGVD2013"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="output_vertical_crs",
            field=models.TextField(
                choices=[
                    ("Ellipsoidal", "ELLIPSOIDAL"),
                    ("EGM96", "EGM96"),
                    ("EGM2008", "EGM2008"),
                    ("AHD71", "AHD71"),
                    ("CGVD2013", "CGVD2013"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
