# Generated by Django 4.2.4 on 2024-11-20 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "processing_workflow_manager",
            "0005_rename_is_gcp_present_mergeddataset_are_gcps_present_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="mergeddataset",
            old_name="number_of_photos",
            new_name="number_of_images",
        ),
    ]
