# Generated by Django 4.2.4 on 2024-11-28 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("org_manager", "0009_rename_features_organisation_feature_flags"),
        (
            "processing_workflow_manager",
            "0007_gcpimagetag_delete_gcpimagetags",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DefaultPresets",
            new_name="DefaultPreset",
        ),
        migrations.RenameModel(
            old_name="OrgPresets",
            new_name="OrgPreset",
        ),
    ]
