# Generated by Django 4.2.4 on 2024-11-28 10:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "processing_workflow_manager",
            "0006_rename_number_of_photos_mergeddataset_number_of_images",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GCPImageTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_x", models.DecimalField(decimal_places=2, max_digits=6)),
                ("image_y", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "gcp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing_workflow_manager.gcp",
                    ),
                ),
                (
                    "geotag_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="processing_workflow_manager.geotagimage",
                    ),
                ),
            ],
            options={
                "unique_together": {("gcp", "geotag_image")},
            },
        ),
        migrations.DeleteModel(
            name="GCPImageTags",
        ),
    ]
