# Generated by Django 4.2.4 on 2024-12-05 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0028_alter_fileinfo_type"),
        (
            "processing_workflow_manager",
            "0007_rename_defaultpresets_defaultpreset_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="output_ortho_tile_zip",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="output_ortho_tile_zip_task",
                to="shared.fileinfo",
            ),
        ),
    ]
