# Generated by Django 4.2.4 on 2024-12-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processing_workflow_manager", "0009_alter_task_output_ortho_tile_zip"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskgeotagimage",
            name="is_used_for_processing",
            field=models.BooleanField(default=True),
        ),
    ]
