# Generated by Django 4.2.4 on 2024-12-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("processing_workflow_manager", "0010_taskgeotagimage_is_used_for_processing"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskgeotagimage",
            name="is_image_aligned",
            field=models.BooleanField(default=False),
        ),
    ]
