version: "3.10"

services:
  redis:
    container_name: redis
    image: redis:alpine3.17
    ports:
      - "6378:6379"

  app:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --reload --log-config log_config.json
    ports:
      - "8000:8000"
    volumes:
      - ./src:/code/src
      - ./requirements.txt:/code/requirements.txt
      - ./config:/code/config
      - ./.coveragerc:/code/.coveragerc
      - ./temp/:/tmp/
    env_file:
      - ".env.local"
    depends_on:
      - redis
