import os
from enum import Enum


class EnvVariable(Enum):
    # Project Configs.
    ALLOWED_CORS_DOMAINS = os.environ[
        "ALLOWED_CORS_DOMAINS"
    ]  # Comma separated allowed hosts string.
    ANALYTICS_ENGINE_URL = os.environ["ANALYTICS_ENGINE_URL"]
    API_ENGINE_DOMAIN = os.environ["API_ENGINE_DOMAIN"]
    CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", None)
    DEBUG = os.environ["DEBUG"]
    ENVIRONMENT = os.environ["ENVIRONMENT"]
    SECRET_KEY = os.environ["SECRET_KEY"]
    SENTRY_DSN = os.environ["SENTRY_DSN"]
    SENTRY_SECURITY_URI = os.environ["SENTRY_SECURITY_URI"]

    # AWS Configs.
    AWS_BATCH_ANALYTICS_ENGINE_JOB_DEFINITION = os.environ.get(
        "AWS_BATCH_ANALYTICS_ENGINE_JOB_DEFINITION", None
    )
    AWS_BATCH_ANALYTICS_ENGINE_JOB_QUEUE = os.environ.get(
        "AWS_BATCH_ANALYTICS_ENGINE_JOB_QUEUE", None
    )
    AWS_BATCH_ANALYTICS_ENGINE_WITH_GPU_JOB_DEFINITION = os.environ.get(
        "AWS_BATCH_ANALYTICS_ENGINE_WITH_GPU_JOB_DEFINITION", None
    )
    AWS_BATCH_ANALYTICS_ENGINE_WITH_GPU_JOB_QUEUE = os.environ.get(
        "AWS_BATCH_ANALYTICS_ENGINE_WITH_GPU_JOB_QUEUE", None
    )
    AWS_BATCH_COG_JOB_DEFINITION = os.environ["AWS_BATCH_COG_JOB_DEFINITION"]
    AWS_BATCH_COG_JOB_QUEUE = os.environ["AWS_BATCH_COG_JOB_QUEUE"]
    AWS_BATCH_MBTILES_JOB_DEFINITION = os.environ.get(
        "AWS_BATCH_MBTILES_JOB_DEFINITION"
    )
    AWS_BATCH_MBTILES_JOB_QUEUE = os.environ.get("AWS_BATCH_MBTILES_JOB_QUEUE")
    AWS_BATCH_SLOPE_MAP_JOB_DEFINITION = os.environ[
        "AWS_BATCH_SLOPE_MAP_JOB_DEFINITION"
    ]
    AWS_BATCH_SLOPE_MAP_JOB_QUEUE = os.environ["AWS_BATCH_SLOPE_MAP_JOB_QUEUE"]
    AWS_BATCH_TT_JOB_DEFINITION = os.environ["AWS_BATCH_TT_JOB_DEFINITION"]
    AWS_BATCH_TT_JOB_QUEUE = os.environ["AWS_BATCH_TT_JOB_QUEUE"]
    AWS_BATCH_VECTOR_TILES_JOB_DEFINITION = os.environ[
        "AWS_BATCH_VECTOR_TILES_JOB_DEFINITION"
    ]
    AWS_BATCH_VECTOR_TILES_JOB_QUEUE = os.environ["AWS_BATCH_VECTOR_TILES_JOB_QUEUE"]
    AWS_EXPORT_FUNCTION = os.environ["AWS_EXPORT_FUNCTION"]
    AWS_LAMBDA_CONTOUR_GENERATOR_FUNCTION = os.environ[
        "AWS_LAMBDA_CONTOUR_GENERATOR_FUNCTION"
    ]
    BUCKET_NAME = os.environ["BUCKET_NAME"]

    # Authentication Configs.
    COGNITO_CLIENT_ID = os.environ.get("COGNITO_CLIENT_ID", None)
    COGNITO_CLIENT_SECRET = os.environ.get("COGNITO_CLIENT_SECRET", None)
    COGNITO_DOMAIN = os.environ.get("COGNITO_DOMAIN", None)
    COGNITO_REDIRECTION_URI = os.environ.get("COGNITO_REDIRECTION_URI", None)
    LOGIN_MODE = os.environ.get("LOGIN_MODE", "Basic")
    MASTER_PASSWORD = os.environ["MASTER_PASSWORD"]
    MICROSERVICE_API_KEY = os.environ["MICROSERVICE_API_KEY"]

    # Email Configs.
    ANALYTICS_REQUEST_RECIPIENT_EMAIL = os.environ.get(
        "ANALYTICS_REQUEST_RECIPIENT_EMAIL", None
    )
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")

    # Processing Configs.
    PROCESSING_MASTER_TOKEN = os.environ["PROCESSING_MASTER_TOKEN"]
    PROCESSING_SERVER_URL = os.environ["PROCESSING_SERVER_URL"]

    # Database Configs.
    DB_HOSTNAME = os.environ["RDS_HOSTNAME"]
    DB_MIGRATE_PASSWORD = os.environ["RDS_MIGRATE_PASSWORD"]
    DB_MIGRATE_USERNAME = os.environ["RDS_MIGRATE_USERNAME"]
    DB_NAME = os.environ["RDS_DB_NAME"]
    DB_PASSWORD = os.environ["RDS_PASSWORD"]
    DB_PORT = os.environ["RDS_PORT"]
    DB_USERNAME = os.environ["RDS_USERNAME"]

    # Processing workflow configs
    AWS_BATCH_EXIF_EXTRACTOR_JOB_DEFINITION = os.environ[
        "AWS_BATCH_EXIF_EXTRACTOR_JOB_DEFINITION"
    ]
    AWS_BATCH_EXIF_EXTRACTOR_JOB_QUEUE = os.environ[
        "AWS_BATCH_EXIF_EXTRACTOR_JOB_QUEUE"
    ]
    AWS_BATCH_DATA_ARCHIVER_JOB_DEFINITION = os.environ[
        "AWS_BATCH_DATA_ARCHIVER_JOB_DEFINITION"
    ]
    AWS_BATCH_DATA_ARCHIVER_JOB_QUEUE = os.environ["AWS_BATCH_DATA_ARCHIVER_JOB_QUEUE"]
    MASTER_SERVER_HOST = os.environ.get("MASTER_SERVER_HOST")
    MCLI_API_KEY = os.environ["MCLI_API_KEY"]
    SOURCE_IMAGES_BUCKET_NAME = os.environ["SOURCE_IMAGES_BUCKET_NAME"]
    OUTPUT_BUCKET_NAME = os.environ["OUTPUT_BUCKET_NAME"]
    LICENSE_BUCKET_NAME = os.environ["LICENSE_BUCKET_NAME"]
    REDIS_HOST_NAME = os.environ["REDIS_HOST_NAME"]
    REDIS_PASSWORD = os.environ.get("REDIS_PASSWORD", "")
    S3_STORAGE_CLASS = os.environ.get("S3_STORAGE_CLASS", "STANDARD_IA")
    SLACK_WEBHOOK_URL = os.environ["SLACK_WEBHOOK_URL"]
    SLACK_TASK_NOTIFICATION_WEBHOOK_URL = os.environ.get(
        "SLACK_TASK_NOTIFICATION_WEBHOOK_URL", ""
    )
    SLACK_METASHAPE_ERRORS_WEBHOOK_URL = os.environ.get(
        "SLACK_METASHAPE_ERRORS_WEBHOOK_URL", ""
    )
