import json
from collections import defaultdict

from django.urls import reverse
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import exception_handler

from rainbow import logger
from shared.exception_handling import ApiError, ApiErrors, SlugMessageMaps
from shared.helpers import slugify

from .helpers import is_json_string


def custom_exception_handler(exc, context):
    exception_class = exc.__class__.__name__
    response = exception_handler(exc, context)
    if exception_class in handlers:
        return handlers[exception_class](exc, context, response)
    else:
        return handle_generic_error(exc, context, response)


# Generic Error Handler.
def handle_generic_error(exc, context, response):
    exception_argument = exc.args[0] if exc.args else ""
    # Handle if the exception is self generated.
    if isinstance(exception_argument, ApiError):
        # Assumes there is only one exception_argument for generic error.
        message = exception_argument.message
        message_slug = exception_argument.slug
        response_status = (
            response.status_code
            if hasattr(response, "status_code")
            else status.HTTP_400_BAD_REQUEST
        )

    # Handle the uncaught exceptions.
    elif not response:
        message_slug = ApiErrors.INTERNAL_SERVER_ERROR.value.slug
        message = ApiErrors.INTERNAL_SERVER_ERROR.value.message
        response_status = status.HTTP_500_INTERNAL_SERVER_ERROR
        # Logging data for internal error on console.
        logger.exception(str(exception_argument))

    # Handle when the error is of response type and  generated by django.
    else:
        detail = str(exception_argument)
        message_slug = slugify(detail)
        message = SlugMessageMaps.get(message_slug, detail)
        response_status = response.status_code

    response_data = {
        "message": message,
        "slug": message_slug,
        "type": exc.__class__.__name__,
    }

    return Response(response_data, status=response_status)


# Error handling for token errors.
def handle_token_error(exc, context, response):
    # If request is to refresh token for a user.
    if context["request"].get_full_path() == reverse("token-refresh"):
        response_data = {
            "message": ApiErrors.TOKEN_EXPIRED.value.message,
            "slug": ApiErrors.TOKEN_EXPIRED.value.slug,
            "type": "TokenBlacklisted",
        }
        return Response(response_data, status=status.HTTP_401_UNAUTHORIZED)

    response_data = {
        "message": ApiErrors.TOKEN_ERROR.value.message,
        "slug": ApiErrors.TOKEN_ERROR.value.slug,
        "type": exc.__class__.__name__,
    }

    return Response(response_data, status=status.HTTP_401_UNAUTHORIZED)


# Error handling for permission errors.
def handle_permission_error(exc, context, response):
    response_data = {
        "message": ApiErrors.PERMISSION_DENIED.value.message,
        "slug": ApiErrors.PERMISSION_DENIED.value.slug,
        "type": exc.__class__.__name__,
    }
    return Response(response_data, status=status.HTTP_403_FORBIDDEN)


# Handle Integrity in model error.
def handle_integrity_error(exc, context, response):
    response_data = {
        "message": ApiErrors.FORM_VALIDATION_ERROR.value.message,
        "slug": ApiErrors.FORM_VALIDATION_ERROR.value.slug,
        "details": {
            "form": {
                "message": ApiErrors.OBJECT_ALREADY_EXISTS.value.message,
                "slug": ApiErrors.OBJECT_ALREADY_EXISTS.value.slug,
            }
        },
        "type": exc.__class__.__name__,
    }
    return Response(response_data, status=status.HTTP_400_BAD_REQUEST)


# Error handling for validation errors.
def handle_validation_error(exc, context, response):
    exception_argument = exc.args[0]
    # Handle if response is None.
    if not response and exception_argument:
        message_slug = slugify(str(exception_argument))
        message = SlugMessageMaps.get(message_slug, exception_argument)
        response_data = {
            "message": message,
            "slug": message_slug,
            "type": exc.__class__.__name__,
        }

    # Handle Model generated errors.
    elif isinstance(exception_argument, ApiError):
        response_data = {
            "message": exception_argument.message,
            "slug": exception_argument.slug,
            "type": exc.__class__.__name__,
        }

    # Assumes there is only one non_field_error.
    elif isinstance(exception_argument, dict) and exception_argument.get(
        "non_field_errors"
    ):
        non_field_error = exception_argument.get("non_field_errors")
        if len(non_field_error) == 1:
            message = non_field_error[0]
            if is_json_string(message):
                api_error = json.loads(message)
                response_data = {
                    "message": api_error.get("message"),
                    "slug": api_error.get("slug"),
                    "type": exc.__class__.__name__,
                    "details": {
                        "form": {
                            "message": api_error.get("message"),
                            "slug": api_error.get("slug"),
                        },
                    },
                }
            else:
                message_slug = slugify(message)
                response_data = {
                    "message": ApiErrors.FORM_VALIDATION_ERROR.value.message,
                    "slug": ApiErrors.FORM_VALIDATION_ERROR.value.slug,
                    "type": exc.__class__.__name__,
                    "details": {
                        "form": {
                            "message": SlugMessageMaps.get(message_slug, message),
                            "slug": message_slug,
                        },
                    },
                }
    else:
        details = defaultdict(list)
        # Converting a dictionary with lists of exceptions into a list of lists of exceptions.
        error_list = (
            [
                exception
                for exception_dict in exception_argument
                for exception in exception_dict.items()
            ]
            if isinstance(exception_argument, list)
            else exception_argument.items()
        )
        for field, error_details in error_list:
            for detail in map(str, error_details):
                # Convert string to json if slug exist in as string dict.
                if "slug" in detail:
                    details[field].append(json.loads(detail))
                else:
                    message_slug = slugify(detail)
                    message = SlugMessageMaps.get(message_slug, detail)
                    details[field].append(
                        {
                            "message": message,
                            "slug": message_slug,
                        }
                    )
        response_data = {
            "message": ApiErrors.FORM_VALIDATION_ERROR.value.message,
            "slug": ApiErrors.FORM_VALIDATION_ERROR.value.slug,
            "type": exc.__class__.__name__,
            "details": dict(details),
        }
    return Response(response_data, status=status.HTTP_400_BAD_REQUEST)


# Handle Unauthenticated user error.
def handle_unauthenticated_error(exc, context, response):
    response_data = {
        "message": ApiErrors.AUTHENTICATION_ERROR.value.message,
        "slug": ApiErrors.AUTHENTICATION_ERROR.value.slug,
        "type": exc.__class__.__name__,
    }
    return Response(response_data, status=status.HTTP_401_UNAUTHORIZED)


# Handle Method Not Allowed  error.
def handle_method_not_allowed(exc, context, response):
    response_data = {
        "message": ApiErrors.METHOD_NOT_ALLOWED.value.message,
        "slug": ApiErrors.METHOD_NOT_ALLOWED.value.slug,
        "type": exc.__class__.__name__,
    }
    return Response(response_data, status=status.HTTP_405_METHOD_NOT_ALLOWED)


# To handle exception from a microservice.
def handle_microservice_exception(exc, context, response):
    microservice_response = exc.args[0]
    status_code = exc.status_code

    if (
        microservice_response.get("data") is not None
        and microservice_response.get("meta") is not None
    ):
        return Response(
            {
                "data": microservice_response["data"],
                "meta": microservice_response["meta"],
            },
            status=microservice_response["meta"]["status_code"],
        )
    else:
        return Response(
            {
                "data": microservice_response.pop("data", {}),
                "meta": {
                    "success": "false",
                    "status_code": exc.status_code,
                    "message": microservice_response,
                    "slug": microservice_response.pop("slug", ""),
                    "type": microservice_response.pop("type", ""),
                    "details": microservice_response.pop("details", {}),
                },
            },
            status=status_code,
        )


handlers = {
    "InvalidToken": handle_token_error,
    "NotAuthenticated": handle_unauthenticated_error,
    "PermissionDenied": handle_permission_error,
    "TokenError": handle_token_error,
    "ValidationError": handle_validation_error,
    "IntegrityError": handle_integrity_error,
    "MethodNotAllowed": handle_method_not_allowed,
    "MicroserviceException": handle_microservice_exception,
}
