# Generated by Django 4.2.4 on 2024-11-12 13:19

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_manager", "0005_auto_20220920_0812"),
        ("layer_manager", "0047_alter_feature_layer"),
        ("iteration_manager", "0023_remove_iteration_serial_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camera_latitude",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=11,
                        validators=[
                            django.core.validators.MinValueValidator(-85.05113),
                            django.core.validators.MaxValueValidator(85.05113),
                        ],
                    ),
                ),
                (
                    "camera_longitude",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=11,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                ("camera_height", models.FloatField()),
                (
                    "camera_heading",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(360),
                        ]
                    ),
                ),
                (
                    "camera_pitch",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ]
                    ),
                ),
                (
                    "camera_roll",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ]
                    ),
                ),
                ("slug", models.CharField(max_length=8, unique=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="project_manager.project",
                    ),
                ),
                (
                    "selected_iteration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="workspaces",
                        to="iteration_manager.iteration",
                    ),
                ),
                (
                    "terrain_iteration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="workspaces_for_terrains",
                        to="iteration_manager.iteration",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WorkspaceLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("show", models.BooleanField()),
                ("z_index", models.IntegerField()),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="layers_workspace",
                        to="layer_manager.layer",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="workspace_layers",
                        to="workspace_manager.workspace",
                    ),
                ),
            ],
            options={
                "unique_together": {("layer", "workspace")},
            },
        ),
    ]
