# Generated by Django 4.2.4 on 2024-11-12 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0047_alter_feature_layer"),
        ("iteration_manager", "0023_remove_iteration_serial_id"),
        ("workspace_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workspacelayer",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="workspacelayer",
            name="dsm_iteration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="workspace_dsm_layers",
                to="iteration_manager.iteration",
            ),
        ),
        migrations.AlterField(
            model_name="workspacelayer",
            name="layer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="workspace_layers",
                to="layer_manager.layer",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspacelayer",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("layer__isnull", False),
                    ("dsm_iteration__isnull", False),
                    _connector="OR",
                ),
                name="layer_or_dsm_iteration_required_in_workspace_layer",
            ),
        ),
    ]
