# Generated by Django 4.2.4 on 2024-12-20 10:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import shared.validators.model_field_validators


class Migration(migrations.Migration):
    dependencies = [
        ("org_manager", "0009_rename_features_organisation_feature_flags"),
        ("shared", "0029_alter_fileinfo_managers_alter_batchjob_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("layer_manager", "0047_alter_feature_layer"),
        ("iteration_manager", "0023_remove_iteration_serial_id"),
        ("workspace_manager", "0002_alter_workspacelayer_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HaulRoad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField(max_length=200)),
                (
                    "vehicle_width",
                    models.DecimalField(
                        decimal_places=2,
                        default=7,
                        help_text="Vehicle width in meters.",
                        max_digits=5,
                    ),
                ),
                (
                    "chainage_interval",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        help_text="Interval in meters.",
                        max_digits=5,
                    ),
                ),
                (
                    "batch_job",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shared.batchjob",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_haulroads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "iteration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iteration_manager.iteration",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HaulRoadType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField()),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="org_manager.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Haul Road Risk Category",
                "verbose_name_plural": "Haul Road Risk Categories",
            },
        ),
        migrations.CreateModel(
            name="HaulRoadRiskAnalysisSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("gradient_analysis", "GRADIENT_ANALYSIS"),
                            ("width_analysis", "WIDTH_ANALYSIS"),
                        ]
                    ),
                ),
                (
                    "min_range",
                    models.TextField(
                        help_text="Enter a minimum risk value or formula. Use <strong>{vehicle_width}</strong> to represent vehicle width. For example: <strong>{vehicle_width} + 5</strong>."
                    ),
                ),
                (
                    "max_range",
                    models.TextField(
                        help_text="Enter a maximum risk value or formula. Use <strong>{vehicle_width}</strong> to represent vehicle width. For example: <strong>{vehicle_width} * 2 + 5</strong>."
                    ),
                ),
                ("risk_category", models.TextField()),
                (
                    "color",
                    models.TextField(
                        validators=[
                            shared.validators.model_field_validators.validate_color_field
                        ]
                    ),
                ),
                (
                    "unit_of_range",
                    models.TextField(
                        choices=[("degrees", "DEGREES"), ("meters", "METERS")]
                    ),
                ),
                (
                    "haul_road_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="workspace_manager.haulroadtype",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="org_manager.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "HRA Risk Setting",
                "verbose_name_plural": "HRA Risk Settings",
            },
        ),
        migrations.CreateModel(
            name="HaulRoadLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("center_line", "CENTER_LINE"),
                            ("edges", "EDGES"),
                            ("gradient_analysis", "GRADIENT_ANALYSIS"),
                            ("width_analysis", "WIDTH_ANALYSIS"),
                            ("median", "MEDIAN"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("importing", "IMPORTING"),
                            ("import_failed", "IMPORT_FAILED"),
                            ("started", "STARTED"),
                            ("processing", "PROCESSING"),
                            ("done", "DONE"),
                            ("failed", "FAILED"),
                            ("pending", "PENDING"),
                        ]
                    ),
                ),
                (
                    "haul_road",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="workspace_manager.haulroad",
                    ),
                ),
                (
                    "layer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="layer_manager.layer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="haulroad",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="workspace_manager.haulroadtype",
            ),
        ),
        migrations.AddField(
            model_name="haulroad",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="updated_haulroads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="haulroadtype",
            constraint=models.UniqueConstraint(
                fields=("name", "org"), name="unique_haul_road_risk_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="haulroadlayer",
            constraint=models.UniqueConstraint(
                fields=("layer_id", "haul_road_id"), name="unique_haul_road_layer"
            ),
        ),
    ]
