# Generated by Django 4.2.4 on 2024-12-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workspace_manager",
            "0003_haulroad_haulroadtype_haulroadriskanalysissettings_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="haulroadtype",
            options={
                "verbose_name": "Haul Road Type",
                "verbose_name_plural": "Haul Road Types",
            },
        ),
        migrations.RemoveConstraint(
            model_name="haulroadtype",
            name="unique_haul_road_risk_category",
        ),
        migrations.AlterField(
            model_name="haulroad",
            name="chainage_interval",
            field=models.DecimalField(
                decimal_places=2, help_text="Interval in meters.", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="haulroad",
            name="vehicle_width",
            field=models.DecimalField(
                decimal_places=2, help_text="Vehicle width in meters.", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="haulroadlayer",
            name="type",
            field=models.TextField(
                choices=[
                    ("center_line", "CENTER_LINE"),
                    ("edges", "EDGES"),
                    ("gradient_analysis", "GRADIENT_ANALYSIS"),
                    ("width_analysis", "WIDTH_ANALYSIS"),
                    ("medians", "MEDIANS"),
                    ("cross_slope_analysis", "CROSS_SLOPE_ANALYSIS"),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="haulroadtype",
            constraint=models.UniqueConstraint(
                fields=("name", "org"), name="unique_haul_road_type"
            ),
        ),
    ]
