# Generated by Django 4.2.4 on 2024-12-24 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspace_manager", "0004_alter_haulroadtype_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="haulroadlayer",
            name="status",
        ),
    ]
