# Generated by Django 4.2.4 on 2024-12-27 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0050_update_get_tile_function"),
        ("workspace_manager", "0005_remove_haulroadlayer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="haulroad",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="haulroad",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="haulroadlayer",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="haulroadlayer",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="haulroadlayer",
            name="haul_road",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="workspace_manager.haulroad",
            ),
        ),
        migrations.AlterField(
            model_name="haulroadlayer",
            name="layer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="layer_manager.layer"
            ),
        ),
    ]
