# Generated by Django 4.2.4 on 2024-12-26 12:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("layer_manager", "0049_alter_feature_options"),
        ("shared", "0029_alter_fileinfo_managers_alter_batchjob_status_and_more"),
        ("iteration_manager", "0023_remove_iteration_serial_id"),
        ("workspace_manager", "0006_haulroad_deleted_at_haulroad_is_deleted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartDetect",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_smart_detect",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "input_ortho_layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="layer_manager.layer",
                    ),
                ),
                (
                    "iteration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="smart_detects",
                        to="iteration_manager.iteration",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="updated_smart_detect",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SmartDetectOutput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("bench_toe_crest", "BENCH_TOE_CREST"),
                            (
                                "building_footprints_or_roof_tops",
                                "BUILDING_FOOTPRINTS_OR_ROOF_TOPS",
                            ),
                            ("drainage_analysis", "DRAINAGE_ANALYSIS"),
                            ("heap_detection", "HEAP_DETECTION"),
                            ("metalled_roads", "METALLED_ROADS"),
                            ("ponds_and_lakes", "PONDS_AND_LAKES"),
                            ("rivers_and_streams", "RIVERS_AND_STREAMS"),
                            ("tree_canopies", "TREE_CANOPIES"),
                            ("unmetalled_roads", "UNMETALLED_ROADS"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "batch_job",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="shared.batchjob",
                    ),
                ),
                (
                    "layers",
                    models.ManyToManyField(
                        related_name="smart_detect_layers", to="layer_manager.layer"
                    ),
                ),
                (
                    "smart_detect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="workspace_manager.smartdetect",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
