# Generated by Django 4.2.4 on 2024-12-27 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0029_alter_fileinfo_managers_alter_batchjob_status_and_more"),
        ("workspace_manager", "0007_smartdetect_smartdetectoutput"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smartdetectoutput",
            name="batch_job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shared.batchjob",
            ),
        ),
    ]
