type: object
properties:
  id:
    type: string
    format: uuid
    readOnly: true
  project:
    type: string
    format: uuid
  name:
    type: string
    maxLength: 100
  base_dsm:
    type: string
    format: uuid
    write_only: true
  dashboard_layer_mapbox_id:
    type: string
    maxLength: 2044
    write_only: true
  type:
    type: string
    enum:
    - "mine_site"
    - "wagon_site"
    - "crushed_site"
    - "uncrushed_site"
    - "urban_land"
  latitude:
    type: number
    format: float
  longitude:
    type: number
    format: float
  boundary:
    type: string
    maxLength: 100
required:
- name
