# Generated by Django 4.1.2 on 2022-10-28 06:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("org_manager", "0005_organisation_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("processing_org_id", models.UUIDField(editable=False)),
                (
                    "processing_org_name",
                    models.CharField(max_length=500, null=True),
                ),
                ("connection_token", models.CharField(max_length=500)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="org_manager.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
