# Generated by Django 4.1.2 on 2022-11-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connection",
            name="processing_org_id",
            field=models.UUIDField(),
        ),
    ]
