# Generated by Django 4.1.2 on 2022-11-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("org_manager", "0005_organisation_features"),
        ("processing_manager", "0002_alter_connection_processing_org_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="connection",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="connection",
            unique_together={("processing_org_id", "org")},
        ),
    ]
