# Generated by Django 3.2.6 on 2022-04-08 11:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("filename", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "STARTED"),
                            ("done", "DONE"),
                            ("failed", "FAILED"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
