# Generated by Django 3.2.6 on 2022-04-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "STARTED"),
                    ("done", "DONE"),
                    ("failed", "FAILED"),
                    ("deleted", "DELETED"),
                ],
                max_length=20,
            ),
        ),
    ]
