# Generated by Django 3.2.6 on 2022-07-05 07:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0003_auto_20220503_1218"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("job_id", models.UUIDField(null=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "STARTED"),
                            ("processing", "PROCESSING"),
                            ("completed", "COMPLETED"),
                            ("failed", "FAILED"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "env_variables",
                    models.JSONField(
                        help_text="\n            List of env variables with name and value. \n            [\n              {\n                'name': 'NAME', \n                'value': 'VALUE'\n              }, ...\n            ]\n            "
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name="fileinfo",
            old_name="path",
            new_name="s3_key",
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "STARTED"),
                    ("processing", "PROCESSING"),
                    ("done", "DONE"),
                    ("failed", "FAILED"),
                    ("deleted", "DELETED"),
                ],
                max_length=20,
            ),
        ),
    ]
