# Generated by Django 3.2.6 on 2022-07-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0004_auto_20220705_0737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchjob",
            name="env_variables",
            field=models.JSONField(
                help_text="\n            List of env variables with name and value.\n            [\n              {\n                'name': 'NAME',\n                'value': 'VALUE'\n              }, ...\n            ]\n            "
            ),
        ),
    ]
