# Generated by Django 3.2.6 on 2022-09-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0005_alter_batchjob_env_variables"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batchjob",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="fileinfo",
            options={"ordering": ("-created_at",)},
        ),
    ]
