# Generated by Django 4.1.2 on 2022-11-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0006_auto_20220920_0812"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileinfo",
            name="batch_job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shared.batchjob",
            ),
        ),
    ]
