# Generated by Django 4.1.2 on 2022-11-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0007_fileinfo_batch_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileinfo",
            name="s3_key",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
