# Generated by Django 4.1.2 on 2022-11-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0008_alter_fileinfo_s3_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("importing", "IMPORTING"),
                    ("import_failed", "IMPORT_FAILED"),
                    ("started", "STARTED"),
                    ("processing", "PROCESSING"),
                    ("done", "DONE"),
                    ("failed", "FAILED"),
                    ("deleted", "DELETED"),
                ],
                max_length=20,
            ),
        ),
    ]
