# Generated by Django 4.1.3 on 2023-01-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0009_alter_fileinfo_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileinfo",
            name="filetype",
            field=models.CharField(
                choices=[
                    ("base_dsm", "BASE_DSM"),
                    ("captured_dsm", "CAPTURED_DSM"),
                    ("legend_image", "LEGEND_IMAGE"),
                    ("mbtiles", "MBTiles"),
                    ("organisation_logo", "ORG_LOGO"),
                    ("orthomosaic", "ORTHOMOSAIC"),
                    ("orthomosaic_cog", "ORTHOMOSAIC_COG"),
                    ("terrain_tiles", "TERRAIN_TILES"),
                    ("vectors", "VECTORS"),
                    ("vector_tiles", "VECTOR_TILES"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fileinfo",
            name="properties",
            field=models.JSONField(null=True),
        ),
    ]
