# Generated by Django 4.1.3 on 2023-01-02 06:47

from django.db import migrations

from ..constants import FileType


def add_filetype_in_fileinfo_data(apps, schema_editor):
    FileInfo = apps.get_model("shared", "FileInfo")
    file_types = FileType.values()

    for file_info in FileInfo.objects.all():
        # Checking if the s3 key is present or not.
        if file_info.s3_key:
            file_type = file_info.s3_key.split("/")[0]

            # If file_type exists in our filetype enum then we will add it to DB.
            if file_type in file_types:
                file_info.filetype = file_type
                file_info.save(update_fields=["filetype"])


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0010_fileinfo_filetype_fileinfo_properties"),
    ]

    operations = [migrations.RunPython(add_filetype_in_fileinfo_data)]
