# Generated by Django 4.1.3 on 2023-01-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0011_auto_20230102_0647"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fileinfo",
            old_name="filename",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="fileinfo",
            old_name="filetype",
            new_name="type",
        ),
        migrations.AddField(
            model_name="fileinfo",
            name="is_folder",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="batchjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "STARTED"),
                    ("processing", "PROCESSING"),
                    ("completed", "COMPLETED"),
                    ("failed", "FAILED"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
