# Generated by Django 4.1.3 on 2023-02-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0012_rename_filename_fileinfo_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileinfo",
            name="type",
            field=models.CharField(
                choices=[
                    ("base_dsm", "BASE_DSM"),
                    ("captured_dsm", "CAPTURED_DSM"),
                    ("captured_dsm_cog", "CAPTURED_DSM_COG"),
                    ("legend_image", "LEGEND_IMAGE"),
                    ("mbtiles", "MBTiles"),
                    ("organisation_logo", "ORG_LOGO"),
                    ("orthomosaic", "ORTHOMOSAIC"),
                    ("orthomosaic_cog", "ORTHOMOSAIC_COG"),
                    ("terrain_tiles", "TERRAIN_TILES"),
                    ("vectors", "VECTORS"),
                    ("vector_tiles", "VECTOR_TILES"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
