# Generated by Django 4.2 on 2023-05-24 04:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0014_alter_fileinfo_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageInfo",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(null=True)),
                ("image_s3_key", models.CharField(max_length=500, null=True)),
                (
                    "thumbnail_s3_key",
                    models.CharField(max_length=500, null=True),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
