# Generated by Django 4.2 on 2023-07-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("org_manager", "0008_organisationaccesstoken"),
        ("shared", "0015_imageinfo_alter_fileinfo_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileinfo",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="org_manager.organisation",
            ),
            preserve_default=False,
        ),
    ]
