# Generated by Django 4.2 on 2023-07-03 09:42

from django.db import migrations


def set_org_to_existing_file_info_rows(apps, schema_editor):
    FileInfoModel = apps.get_model("shared", "FileInfo")
    for file_info in FileInfoModel.objects.all():
        # Fetching data using related name of foreign key relation.
        if org := file_info.organisation_set.first():
            pass

        elif site := file_info.base_dsm.first():
            org = site.project.org

        elif site := file_info.legend_image.first():
            org = site.project.org

        elif iteration := file_info.captured_dsm_iteration.first():
            org = iteration.site.project.org

        elif iteration := file_info.captured_dsm_cog_iteration.first():
            org = iteration.site.project.org

        elif iteration := file_info.ortho_iteration.first():
            org = iteration.site.project.org

        # Fetching data using related name of one and one relation.
        elif hasattr(file_info, "layerfile"):
            org = file_info.layerfile.layer.site.project.org

        else:
            continue

        print(f"Setting organisation of {file_info} as {org}")
        file_info.org = org
        file_info.save(update_fields=["org"])


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0016_fileinfo_org"),
        ("org_manager", "0008_organisationaccesstoken"),
        ("project_manager", "0005_auto_20220920_0812"),
        ("site_manager", "0016_alter_sitekpi_actual_ore_production_and_more"),
        ("iteration_manager", "0017_alter_heapboundary_geometry"),
        (
            "layer_manager",
            "0036_remove_layer_raster_file_remove_layer_vector_file_and_more",
        ),
    ]
    operations = [
        migrations.RunPython(set_org_to_existing_file_info_rows),
    ]
