# Generated by Django 4.2 on 2023-08-04 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shared", "0017_auto_20230705_1227"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileinfo",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="type",
            field=models.CharField(
                choices=[
                    ("base_dsm", "BASE_DSM"),
                    ("captured_dsm", "CAPTURED_DSM"),
                    ("captured_dsm_cog", "CAPTURED_DSM_COG"),
                    ("legend_image", "LEGEND_IMAGE"),
                    ("mbtiles", "MBTiles"),
                    ("organisation_logo", "ORG_LOGO"),
                    ("orthomosaic", "ORTHOMOSAIC"),
                    ("orthomosaic_cog", "ORTHOMOSAIC_COG"),
                    ("slope_map", "SLOPE_MAP"),
                    ("terrain_tiles", "TERRAIN_TILES"),
                    ("vector_tiles", "VECTOR_TILES"),
                    ("vectors", "VECTORS"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
