# Generated by Django 4.2 on 2023-08-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0018_fileinfo_created_by_alter_fileinfo_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileinfo",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fileinfo",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("importing", "IMPORTING"),
                    ("import_failed", "IMPORT_FAILED"),
                    ("started", "STARTED"),
                    ("processing", "PROCESSING"),
                    ("done", "DONE"),
                    ("failed", "FAILED"),
                ],
                max_length=20,
            ),
        ),
    ]
