# Generated by Django 4.2 on 2023-08-07 08:52

from django.db import migrations


# Update is_deleted field for all the deleted files.
def set_is_deleted(apps, schema_editor):
    FileInfo = apps.get_model("shared", "FileInfo")
    file_info_list = FileInfo.objects.filter(status="deleted")
    file_info_list.update(is_deleted=True)


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0019_fileinfo_deleted_at_fileinfo_is_deleted_and_more"),
    ]

    operations = [
        migrations.RunPython(set_is_deleted),
    ]
