# Generated by Django 4.2.3 on 2023-09-04 10:44

from django.db import migrations

from rainbow import logger
from shared.constants import FileType


def delete_siblings_of_deleted_files(apps, schema_editor):
    FileInfoModel = apps.get_model("shared", "FileInfo")

    USER_DELETEABLE_LAYER_FILE_TYPES = [
        FileType.ORTHOMOSAIC.value,
        FileType.MBTiles.value,
    ]

    for file_info in FileInfoModel.objects.filter(
        is_deleted=True, type__in=USER_DELETEABLE_LAYER_FILE_TYPES
    ):
        if not hasattr(file_info, "layerfile"):
            continue

        layer_file = file_info.layerfile
        layer = layer_file.layer

        sibling_layer_files = layer.layer_files.exclude(id=layer_file.id)

        logger.info(f"Deleting siblings of deleted file: {file_info.id}")
        for sibling_layer_file in sibling_layer_files:
            logger.info(f"Deleting layer file: {sibling_layer_file.id}")
            sibling_layer_file.file_info.is_deleted = True
            sibling_layer_file.file_info.save()

            sibling_layer_file.is_deleted = True
            sibling_layer_file.save()


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0020_set_is_deleted_for_deleted_files"),
    ]

    operations = [migrations.RunPython(delete_siblings_of_deleted_files)]
