# Generated by Django 4.2.4 on 2023-09-21 08:28

import django.contrib.postgres.fields
from django.db import migrations, models

import shared.constants.files


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0021_delete_siblings_of_deleted_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileinfo",
            name="errors",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SlugField(
                    max_length=100,
                    validators=[shared.constants.files.FileError.validate_slug],
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="type",
            field=models.CharField(
                choices=[
                    ("base_dsm", "BASE_DSM"),
                    ("captured_dsm", "CAPTURED_DSM"),
                    ("captured_dsm_cog", "CAPTURED_DSM_COG"),
                    ("legend_image", "LEGEND_IMAGE"),
                    ("mbtiles", "MBTiles"),
                    ("organisation_logo", "ORG_LOGO"),
                    ("orthomosaic", "ORTHOMOSAIC"),
                    ("orthomosaic_cog", "ORTHOMOSAIC_COG"),
                    ("slope_map", "SLOPE_MAP"),
                    ("terrain_tiles", "TERRAIN_TILES"),
                    ("vector_tiles", "VECTOR_TILES"),
                    ("vectors", "VECTORS"),
                    ("temporary", "TEMPORARY"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
