# Generated by Django 4.2.7 on 2024-02-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0022_fileinfo_errors_alter_fileinfo_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileinfo",
            name="name",
            field=models.CharField(max_length=250),
        ),
    ]
