# Generated by Django 4.2.4 on 2024-04-02 10:41

from django.db import migrations, models

import shared.models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0023_alter_fileinfo_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileinfo",
            name="bucket_name",
            field=models.TextField(default=shared.models.get_default_bucket_name),
        ),
        migrations.AddField(
            model_name="imageinfo",
            name="bucket_name",
            field=models.TextField(default=shared.models.get_default_bucket_name),
        ),
    ]
