# Generated by Django 4.2.4 on 2024-09-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0025_batchjob_benchmarks_batchjob_instance_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchjob",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="batchjob",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
