# Generated by Django 4.2.4 on 2024-12-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0027_alter_fileinfo_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileinfo",
            name="type",
            field=models.CharField(
                choices=[
                    ("base_dsm", "BASE_DSM"),
                    ("captured_dsm", "CAPTURED_DSM"),
                    ("captured_dsm_cog", "CAPTURED_DSM_COG"),
                    ("legend_image", "LEGEND_IMAGE"),
                    ("mbtiles", "MBTiles"),
                    ("images_folder", "IMAGES_FOLDER"),
                    ("organisation_logo", "ORG_LOGO"),
                    ("orthomosaic", "ORTHOMOSAIC"),
                    ("orthomosaic_cog", "ORTHOMOSAIC_COG"),
                    ("slope_map", "SLOPE_MAP"),
                    ("terrain_tiles", "TERRAIN_TILES"),
                    ("vector_tiles", "VECTOR_TILES"),
                    ("vectors", "VECTORS"),
                    ("project_file", "PROJECT_FILE"),
                    ("temporary", "TEMPORARY"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
