# Generated by Django 4.2.4 on 2024-12-13 14:54

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0028_alter_fileinfo_type"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="fileinfo",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="batchjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("started", "STARTED"),
                    ("processing", "PROCESSING"),
                    ("completed", "COMPLETED"),
                    ("failed", "FAILED"),
                    ("cancelled", "CANCELLED"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("importing", "IMPORTING"),
                    ("import_failed", "IMPORT_FAILED"),
                    ("started", "STARTED"),
                    ("processing", "PROCESSING"),
                    ("done", "DONE"),
                    ("failed", "FAILED"),
                    ("pending", "PENDING"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fileinfo",
            name="type",
            field=models.CharField(
                choices=[
                    ("all_outputs", "ALL_OUTPUTS"),
                    ("base_dsm", "BASE_DSM"),
                    ("captured_dsm", "CAPTURED_DSM"),
                    ("captured_dsm_cog", "CAPTURED_DSM_COG"),
                    ("legend_image", "LEGEND_IMAGE"),
                    ("mbtiles", "MBTiles"),
                    ("images_folder", "IMAGES_FOLDER"),
                    ("organisation_logo", "ORG_LOGO"),
                    ("orthomosaic", "ORTHOMOSAIC"),
                    ("orthomosaic_cog", "ORTHOMOSAIC_COG"),
                    ("ortho_tiles", "ORTHO_TILES"),
                    ("slope_map", "SLOPE_MAP"),
                    ("terrain_tiles", "TERRAIN_TILES"),
                    ("vector_tiles", "VECTOR_TILES"),
                    ("vectors", "VECTORS"),
                    ("point_cloud", "POINT_CLOUD"),
                    ("report", "REPORT"),
                    ("project_file", "PROJECT_FILE"),
                    ("outputs_folder", "OUTPUTS_FOLDER"),
                    ("temporary", "TEMPORARY"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
