# Generated by Django 3.2.6 on 2022-04-15 12:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("site_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chart_data", models.TextField()),
                ("chart_cat", models.CharField(max_length=50, null=True)),
                ("financial_year_ending", models.IntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_manager.site",
                    ),
                ),
            ],
        ),
    ]
