# Generated by Django 3.2.6 on 2022-04-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="financial_year_ending",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="month",
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
