# Generated by Django 4.1.3 on 2023-04-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_auto_20220420_0747"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dashboard",
        ),
    ]
