from enum import Enum


class VectorDriver(Enum):
    AERONAV_FAA = "AeronavFAA"
    BNA = "BNA"
    CAD_CORP_SIS = "CadCorpSIS"
    CARTO_DB = "CartoDB"
    CLOUDANT = "Cloudant"
    COUCH_DB = "CouchDB"
    CRITEO = "Criteo"
    CSV = "CSV"
    CSW = "CSW"
    DGN = "DGN"
    DXF = "DXF"
    EEDA = "EEDA"
    ELASTIC_SEARCH = "ElasticSearch"
    ESRI_SHAPEFILE = "ESRI Shapefile"
    GEO_CONCEPT = "Geoconcept"
    GEO_JSON = "GeoJSON"
    GEO_RSS = "GeoRSS"
    GFT = "GFT"
    GME = "GME"
    GML = "GML"
    GPKG = "GPKG"
    GPS_BABEL = "GPSBabel"
    GPX = "GPX"
    GRASS = "GRASS"
    I_FLIGHT_PLANNER = "iFlightPlanner"
    INGRES = "INGRES"
    KING_CHAOS = "KingChaos"
    KML = "KML"
    MAPINFO_FILE = "MapInfo File"
    MS_SQL_SPATIAL = "MSSQLSpatial"
    MS_SQL_SPATIAL_OGR = "MSSQLSpatial OGR"
    MVT = "MVT"
    MY_SQL = "MySQL"
    NAS = "NAS"
    OCI = "OCI"
    ODBC = "ODBC"
    OGDI = "OGDI"
    OPEN_FILE_GDB = "OpenFileGDB"
    PCIDSK = "PCIDSK"
    PDF = "PDF"
    PGEO = "PGeo"
    PL_SCENES = "PLScenes"
    POSTGRES_SQL = "PostgreSQL"
    S57 = "S57"
    SDTS = "SDTS"
    SEGUKOOA = "SEGUKOOA"
    SEGY = "SEGY"
    SELAFIN = "Selafin"
    SOSI = "SOSI"
    SQLITE = "SQLite"
    SUA = "SUA"
    SVG = "SVG"
    SXF = "SXF"
    TIGER = "TIGER"
    VDV = "VDV"
    VRT = "VRT"
    WASP = "WAsP"
    WFS = "WFS"
    WMS = "WMS"
    XLS = "XLS"
    XLSX = "XLSX"
    XPLANE = "XPlane"


VECTOR_DRIVER_EXTENSION = {
    VectorDriver.ESRI_SHAPEFILE: "shp",
    VectorDriver.DXF: "dxf",
    VectorDriver.KML: "kml",
}
