# Generated by Django 3.2.6 on 2022-04-12 07:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("org_manager", "0001_initial"),
        ("shared", "0002_alter_fileinfo_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("mine_site", "MineSite"),
                            ("wagon_site", "WagonSite"),
                            ("crushed_site", "CrushedSite"),
                            ("uncrushed_site", "UncrushedSite"),
                            ("urban_land", "UrbanLand"),
                        ],
                        default="mine_site",
                        max_length=30,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("boundary", models.CharField(max_length=100)),
                (
                    "dashboard_layer_mapbox_id",
                    models.CharField(blank=True, max_length=2044, null=True),
                ),
                (
                    "base_dsm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="org_manager.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
