# Generated by Django 3.2.6 on 2022-04-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="type",
            field=models.CharField(
                choices=[
                    ("mine_site", "MINE_SITE"),
                    ("wagon_site", "WAGON_SITE"),
                    ("crushed_site", "CRUSHED_SITE"),
                    ("uncrushed_site", "UNCRUSHED_SITE"),
                    ("urban_land", "URBAN_LAND"),
                ],
                default="mine_site",
                max_length=30,
            ),
        ),
    ]
