# Generated by Django 3.2.6 on 2022-04-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_manager", "0002_alter_site_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="boundary",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
