# Generated by Django 3.2.6 on 2022-04-26 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0002_create_default_project_for_each_org"),
        ("site_manager", "0003_auto_20220421_0521"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="project_manager.project",
            ),
        ),
    ]
