# Generated by Django 3.2.6 on 2022-04-26 10:19

from django.db import migrations


def add_project(apps, schema_editor):
    Project = apps.get_model("project_manager", "Project")
    Site = apps.get_model("site_manager", "Site")

    for site in Site.objects.all():
        project = Project.objects.filter(org=site.org).first()
        site.project = project
        site.save(update_fields=["project"])


class Migration(migrations.Migration):

    dependencies = [
        ("site_manager", "0004_site_project"),
    ]

    operations = [migrations.RunPython(add_project)]
