# Generated by Django 3.2.6 on 2022-04-26 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_manager", "0005_add_project_to_sites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="org",
        ),
    ]
