# Generated by Django 3.2.6 on 2022-05-02 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0003_alter_project_options"),
        ("site_manager", "0006_remove_site_org"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="project_manager.project",
            ),
        ),
    ]
