# Generated by Django 3.2.6 on 2022-08-01 12:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0006_alter_usergroup_users"),
        ("project_manager", "0004_projectpermission"),
        ("site_manager", "0008_auto_20220503_1218"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("can_view", models.BooleanField()),
                ("can_manage_iterations_and_layers", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="project_manager.project",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="site_manager.site",
                    ),
                ),
                (
                    "user_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_permissions",
                        to="user_manager.usergroup",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "unique_together": {("site", "user_group")},
            },
        ),
    ]
