# Generated by Django 3.2.6 on 2022-09-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site_manager", "0009_sitepermission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="sitepermission",
            options={"ordering": ("-created_at",)},
        ),
    ]
