# Generated by Django 4.1.1 on 2022-10-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0006_auto_20220920_0812"),
        ("site_manager", "0010_auto_20220920_0812"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="legend_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legend_image",
                to="shared.fileinfo",
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="base_dsm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_dsm",
                to="shared.fileinfo",
            ),
        ),
    ]
