# Generated by Django 4.1.3 on 2023-02-12 16:51

import uuid

import django.db.models.deletion
from django.db import migrations, models

import shared.validators.model_field_validators


class Migration(migrations.Migration):

    dependencies = [
        ("site_manager", "0011_site_legend_image_alter_site_base_dsm"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionTarget",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            shared.validators.model_field_validators.validate_month_field
                        ]
                    ),
                ),
                (
                    "overburden_production",
                    models.FloatField(help_text="Unit is cubic meters"),
                ),
                (
                    "ore_production",
                    models.FloatField(help_text="Unit is cubic meters"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="site_manager.site",
                    ),
                ),
            ],
            options={
                "unique_together": {("site", "year", "month")},
            },
        ),
    ]
