# Generated by Django 4.1.3 on 2023-03-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_manager", "0012_productiontarget"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitepermission",
            name="access_type",
            field=models.CharField(
                choices=[("basic", "BASIC"), ("advance", "ADVANCE")],
                default="advance",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="sitepermission",
            name="can_manage_iterations_and_layers",
            field=models.BooleanField(
                help_text=" \n            AccessType: ALL ACCESS ---> edit access for all iterations and layers.\n            AccessType: TAG BASED ACCESS FOR LAYER ---> create and edit access for all iterations and layers.\n        "
            ),
        ),
    ]
