# Generated by Django 4.1.3 on 2023-03-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_manager", "0013_sitepermission_access_type_and_more"),
    ]

    operations = [
        migrations.RenameModel("ProductionTarget", "ProductionKPI"),
        migrations.RenameField(
            model_name="ProductionKPI",
            old_name="overburden_production",
            new_name="target_overburden_production",
        ),
        migrations.RenameField(
            model_name="ProductionKPI",
            old_name="ore_production",
            new_name="target_ore_production",
        ),
        migrations.AddField(
            model_name="ProductionKPI",
            name="actual_overburden_production",
            field=models.FloatField(null=True, help_text="Unit is cubic meters"),
        ),
        migrations.AddField(
            model_name="ProductionKPI",
            name="actual_ore_production",
            field=models.FloatField(null=True, help_text="Unit is cubic meters"),
        ),
        migrations.AlterField(
            model_name="sitepermission",
            name="can_manage_iterations_and_layers",
            field=models.BooleanField(
                help_text="\n            AccessType: BASIC ---> edit access for all iterations and layers.\n            AccessType: ADVANCE ---> create and edit access for all iterations and layers.\n        "
            ),
        ),
    ]
