# Generated by Django 4.1.3 on 2023-04-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_manager", "0014_productionkpi_and_more"),
    ]

    operations = [
        migrations.RenameModel("ProductionKPI", "SiteKPI"),
        migrations.AddField(
            model_name="sitekpi",
            name="haul_road_distance_under_gradient_issue",
            field=models.FloatField(help_text="Unit is kilometers", null=True),
        ),
        migrations.AddField(
            model_name="sitekpi",
            name="haul_road_distance_under_width_issue",
            field=models.FloatField(help_text="Unit is kilometers", null=True),
        ),
        migrations.AddField(
            model_name="sitekpi",
            name="stock_volume",
            field=models.FloatField(help_text="Unit is tonnes", null=True),
        ),
        migrations.AlterField(
            model_name="sitekpi",
            name="target_ore_production",
            field=models.FloatField(help_text="Unit is cubic meters", null=True),
        ),
        migrations.AlterField(
            model_name="sitekpi",
            name="target_overburden_production",
            field=models.FloatField(help_text="Unit is cubic meters", null=True),
        ),
    ]
