# Generated by Django 4.2 on 2023-05-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_manager", "0015_merge_all_kpi_models_into_sitekpi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitekpi",
            name="actual_ore_production",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="sitekpi",
            name="actual_overburden_production",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="sitekpi",
            name="haul_road_distance_under_gradient_issue",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="sitekpi",
            name="haul_road_distance_under_width_issue",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="sitekpi",
            name="stock_volume",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="sitekpi",
            name="target_ore_production",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="sitekpi",
            name="target_overburden_production",
            field=models.FloatField(null=True),
        ),
    ]
