# Generated by Django 4.2.4 on 2024-05-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site_manager", "0016_alter_sitekpi_actual_ore_production_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="site",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
