# Generated by Django 3.2.6 on 2022-07-19 13:24

from django.db import migrations

from user_manager.constants import UserType


def create_org_admin_for_orgs(apps, schema_editor):
    CustomUser = apps.get_model("user_manager", "CustomUser")
    Organisation = apps.get_model("org_manager", "Organisation")
    for org in Organisation.objects.all():
        user = CustomUser.objects.filter(org=org).first()
        if user:
            user.type = UserType.ORG_ADMIN.value
            user.save(update_fields=["type"])


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0003_customuser_type"),
    ]

    operations = [
        migrations.RunPython(create_org_admin_for_orgs),
    ]
