# Generated by Django 3.2.6 on 2022-07-29 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0005_usergroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergroup",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="groups", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
