# Generated by Django 3.2.6 on 2022-08-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0004_accesstag"),
        ("user_manager", "0006_alter_usergroup_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="access_tags",
            field=models.ManyToManyField(
                blank=True, related_name="groups", to="layer_manager.AccessTag"
            ),
        ),
    ]
