# Generated by Django 3.2.6 on 2022-09-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0007_usergroup_access_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usergroup",
            options={"ordering": ("-created_at",)},
        ),
    ]
