# Generated by Django 4.2.4 on 2023-12-23 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_manager", "0008_alter_usergroup_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["first_name", "last_name", "created_at"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
    ]
