# Generated by Django 3.2.6 on 2022-04-20 10:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iteration_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("source_id", models.CharField(max_length=100, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("base", "BASE"), ("overlay", "OVERLAY")],
                        max_length=100,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("mapbox_street_layer", "MAPBOX_STREET_LAYER"),
                            ("bing_base_layer", "BING_BASE_LAYER"),
                            ("open_street_map", "OPEN_STREET_MAP"),
                            (
                                "mapbox_styled_map_layers",
                                "MAPBOX_STYLED_MAP_LAYERS",
                            ),
                            ("dtm_cesium_layers", "DTM_CESIUM_LAYERS"),
                        ],
                        max_length=100,
                    ),
                ),
                ("index", models.IntegerField(null=True)),
                ("overlay_id", models.CharField(max_length=100, null=True)),
                (
                    "iteration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="iteration_manager.iteration",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
            },
        ),
    ]
