# Generated by Django 3.2.6 on 2022-05-17 09:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0002_auto_20220503_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(
                null=True, srid=4326
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="category",
            field=models.CharField(
                choices=[("base", "BASE"), ("overlay", "OVERLAY")],
                default="overlay",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("mapbox_street_layer", "MAPBOX_STREET_LAYER"),
                    ("bing_base_layer", "BING_BASE_LAYER"),
                    ("open_street_map", "OPEN_STREET_MAP"),
                    ("mapbox_styled_map_layers", "MAPBOX_STYLED_MAP_LAYERS"),
                    ("dtm_cesium_layers", "DTM_CESIUM_LAYERS"),
                    ("vector", "VECTOR"),
                    ("orthomosaic", "ORTHOMOSAIC"),
                    ("dsm", "DSM"),
                ],
                max_length=100,
            ),
        ),
    ]
