# Generated by Django 3.2.6 on 2022-08-22 07:04

import uuid

import django.db.models.deletion
from django.db import migrations, models

import shared.validators


class Migration(migrations.Migration):

    dependencies = [
        ("org_manager", "0002_auto_20220503_1218"),
        ("layer_manager", "0003_auto_20220517_0918"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=15,
                        validators=[shared.validators.validate_no_space],
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        max_length=9,
                        validators=[shared.validators.validate_color_field],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="org_manager.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("name", "org")},
            },
        ),
    ]
