# Generated by Django 3.2.6 on 2022-08-30 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_manager", "0009_sitepermission"),
        ("layer_manager", "0004_accesstag"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="access_tags",
            field=models.ManyToManyField(
                related_name="layers", to="layer_manager.AccessTag"
            ),
        ),
        migrations.AddField(
            model_name="layer",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="site_manager.site",
            ),
        ),
    ]
