# Generated by Django 3.2.6 on 2022-09-13 11:47

from django.db import migrations, models

import shared.validators


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0004_accesstag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstag",
            name="name",
            field=models.CharField(
                max_length=32,
                validators=[shared.validators.validate_no_space],
            ),
        ),
    ]
