# Generated by Django 3.2.6 on 2022-09-01 13:30

from django.db import migrations


def add_site_in_layers(apps, schema_editor):
    LayerModel = apps.get_model("layer_manager", "Layer")

    for layer in LayerModel.objects.all():
        layer.site = layer.iteration.site
        layer.save(update_fields=["site"])


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0005_auto_20220830_2020"),
    ]

    operations = [
        migrations.RunPython(add_site_in_layers),
    ]
