# Generated by Django 3.2.6 on 2022-09-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0006_auto_20220901_1330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layer",
            name="access_tags",
            field=models.ManyToManyField(
                blank=True, related_name="layers", to="layer_manager.AccessTag"
            ),
        ),
    ]
