# Generated by Django 3.2.6 on 2022-09-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0005_alter_accesstag_name"),
        ("layer_manager", "0007_alter_layer_access_tags"),
    ]

    operations = []
