# Generated by Django 3.2.6 on 2022-09-16 06:27

from django.db import migrations

from ..constants import LayerType


# Remove all base layers form db.
def remove_base_layers_data(apps, schema_editor):
    LayerModel = apps.get_model("layer_manager", "Layer")
    LayerModel.objects.filter(category="base").delete()


# For every layer, which has ORTHO in name, set type as orthomosaic.
def set_type_of_orthomosaic(apps, schema_editor):
    LayerModel = apps.get_model("layer_manager", "Layer")
    layers = LayerModel.objects.filter(name__icontains="ortho")
    layers.update(source_type=LayerType.ORTHOMOSAIC.value)


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0008_merge_20220917_0913"),
    ]

    operations = [
        migrations.RunPython(remove_base_layers_data),
        migrations.RunPython(set_type_of_orthomosaic),
    ]
