# Generated by Django 3.2.6 on 2022-09-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0009_auto_20220916_0627"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layer",
            name="category",
        ),
        migrations.RemoveField(
            model_name="layer",
            name="overlay_id",
        ),
        migrations.AlterField(
            model_name="layer",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("dtm_cesium_layers", "DTM_CESIUM_LAYERS"),
                    ("mapbox_styled_map_layers", "MAPBOX_STYLED_MAP_LAYERS"),
                    ("orthomosaic", "ORTHOMOSAIC"),
                    ("vector", "VECTOR"),
                ],
                max_length=100,
            ),
        ),
    ]
