# Generated by Django 3.2.6 on 2022-09-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0010_auto_20220916_0656"),
    ]

    operations = [
        migrations.RenameField(
            model_name="layer",
            old_name="source_type",
            new_name="type",
        ),
    ]
