# Generated by Django 3.2.6 on 2022-09-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0011_rename_source_type_layer_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accesstag",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="layer",
            options={"ordering": ("-created_at",)},
        ),
    ]
