# Generated by Django 4.1.1 on 2022-10-05 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0006_auto_20220920_0812"),
        ("layer_manager", "0012_auto_20220920_0812"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="mbtiles",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shared.fileinfo",
            ),
        ),
    ]
