# Generated by Django 4.1.2 on 2022-11-16 06:57

from django.db import migrations

from ..constants import LayerType

# Update all the occurences of layer type "mapbox_styled_map_layers" with "mapbox".


def set_type_of_mapbox(apps, schema_editor):
    LayerModel = apps.get_model("layer_manager", "Layer")
    layers = LayerModel.objects.filter(type="mapbox_styled_map_layers")
    layers.update(type=LayerType.MAPBOX.value)


# Update all the occurences of layer type "dtm_cesium_layers" with "cesium".


def set_type_of_cesium(apps, schema_editor):
    LayerModel = apps.get_model("layer_manager", "Layer")
    layers = LayerModel.objects.filter(type="dtm_cesium_layers")
    layers.update(type=LayerType.CESIUM.value)


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0013_layer_mbtiles"),
    ]

    operations = [
        migrations.RunPython(set_type_of_mapbox),
        migrations.RunPython(set_type_of_cesium),
    ]
