# Generated by Django 4.1.2 on 2022-11-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0014_auto_20221116_0657"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="properties",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="layer",
            name="type",
            field=models.CharField(
                choices=[
                    ("cesium", "CESIUM"),
                    ("mapbox", "MAPBOX"),
                    ("orthomosaic", "ORTHOMOSAIC"),
                    ("vector", "VECTOR"),
                    ("mbtiles", "MBTILES"),
                ],
                max_length=100,
            ),
        ),
    ]
