# Generated by Django 4.1.3 on 2022-12-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0015_layer_properties_alter_layer_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="layer",
            old_name="mbtiles",
            new_name="vector_file",
        ),
        migrations.AddField(
            model_name="layer",
            name="styles",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="layer",
            name="type",
            field=models.CharField(
                choices=[
                    ("cesium", "CESIUM"),
                    ("mapbox", "MAPBOX"),
                    ("orthomosaic", "ORTHOMOSAIC"),
                    ("vector", "VECTOR"),
                    ("mbtiles", "MBTILES"),
                    ("contour", "CONTOUR"),
                ],
                max_length=100,
            ),
        ),
    ]
