# Generated by Django 4.1.3 on 2023-01-04 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "iteration_manager",
            "0008_rename_volume_heapboundary_cut_volume_and_more",
        ),
        ("shared", "0012_rename_filename_fileinfo_name_and_more"),
        ("site_manager", "0011_site_legend_image_alter_site_base_dsm"),
        (
            "layer_manager",
            "0016_rename_mbtiles_layer_vector_file_layer_styles_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="vector_tiles",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tiles_layers",
                to="shared.fileinfo",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="iteration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="layers",
                to="iteration_manager.iteration",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="layers",
                to="site_manager.site",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="vector_file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="layers",
                to="shared.fileinfo",
            ),
        ),
    ]
