# Generated by Django 4.1.3 on 2023-01-05 10:11

from django.db import migrations

from rainbow.env_variables import EnvVariable
from shared.constants import FileStatus, FileType

from ..constants import LayerType


def get_env_variable(env_variables_list: list, name: str) -> dict:
    for env_variable in env_variables_list:
        if env_variable["name"] == name:
            return env_variable.get("value")


# moving all extracted mbtiles from vector file BatchJob table to vector_tiles FileInfo table.
def move_vector_tiles_from_batch_job_to_file_info(apps, schema_editor):
    LayerModel = apps.get_model("layer_manager", "Layer")
    FileInfoModel = apps.get_model("shared", "FileInfo")

    layers = LayerModel.objects.filter(type=LayerType.MBTILES.value)

    for layer in layers:
        mbtiles_file = layer.vector_file
        if mbtiles_file and mbtiles_file.batch_job:
            vector_tiles_s3_key_with_bucket_name = get_env_variable(
                mbtiles_file.batch_job.env_variables, "OUTPUT_S3_KEY"
            )
            vector_tiles_s3_key = vector_tiles_s3_key_with_bucket_name.replace(
                f"{EnvVariable.BUCKET_NAME.value}/", ""
            )

            vector_tiles_file_info = FileInfoModel.objects.create(
                name=f"{layer.name}-tiles",
                type=FileType.VECTOR_TILES.value,
                s3_key=vector_tiles_s3_key,
                is_folder=True,
                status=FileStatus.DONE.value,
            )

            layer.vector_tiles = vector_tiles_file_info
            layer.save(update_fields=["vector_tiles"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "layer_manager",
            "0017_layer_vector_tiles_alter_layer_iteration_and_more",
        ),
    ]

    operations = [migrations.RunPython(move_vector_tiles_from_batch_job_to_file_info)]
