# Generated by Django 4.1.3 on 2023-01-19 11:42


from django.db import migrations


def moveLayerGeometryToFeature(apps, schema_editor):
    # Get models.
    Layer = apps.get_model("layer_manager", "Layer")
    Feature = apps.get_model("layer_manager", "Feature")

    # Loop on all layers.
    for layer in Layer.objects.all():
        if layer.geometry:
            # Create a Feature object using layer geometry and layer_id.
            Feature.objects.create(geometry=layer.geometry, layer=layer)


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0019_create_feature_model"),
    ]

    operations = [
        migrations.RunPython(moveLayerGeometryToFeature),
    ]
