# Generated by Django 4.1.3 on 2023-02-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0020_move_layer_geometry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layer",
            name="geometry",
        ),
    ]
