# Generated by Django 4.1.3 on 2023-02-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0021_remove_layer_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="features_styles",
            field=models.JSONField(
                null=True,
            ),
        ),
    ]
