# Generated by Django 4.1.3 on 2023-02-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0022_layer_features_styles"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="properties",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="feature",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TextBox", "TEXT_BOX"),
                    ("Point", "POINT"),
                    ("LineString", "LINE_STRING"),
                    ("Polygon", "POLYGON"),
                ],
                max_length=50,
            ),
        ),
    ]
