# Generated by Django 4.1.3 on 2023-02-21 03:39

from django.db import migrations


# Adding type to features.
def add_type_to_features(apps, schema_editor):
    FeatureModel = apps.get_model("layer_manager", "Feature")
    for feature in FeatureModel.objects.all():
        feature.type = feature.geometry.geom_type
        feature.save()


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0023_feature_properties_feature_type"),
    ]

    operations = [migrations.RunPython(add_type_to_features)]
