# Generated by Django 4.1.3 on 2023-02-21 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0014_alter_fileinfo_type"),
        ("layer_manager", "0024_auto_20230221_0339"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="raster_file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="raster_layer",
                to="shared.fileinfo",
            ),
        ),
        migrations.AlterField(
            model_name="layer",
            name="type",
            field=models.CharField(
                choices=[
                    ("cesium", "CESIUM"),
                    ("mapbox", "MAPBOX"),
                    ("orthomosaic", "ORTHOMOSAIC"),
                    ("vector", "VECTOR"),
                    ("mbtiles", "MBTILES"),
                    ("contour", "CONTOUR"),
                    ("slope_map", "SLOPE_MAP"),
                ],
                max_length=100,
            ),
        ),
    ]
