# Generated by Django 4.1.3 on 2023-02-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0025_layer_raster_file_alter_layer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="area_category",
            field=models.CharField(
                choices=[
                    ("other", "OTHER"),
                    ("planned_and_active", "PLANNED_AND_ACTIVE"),
                    ("planned_and_inactive", "PLANNED_AND_INACTIVE"),
                    ("unplanned_and_active", "UNPLANNED_AND_ACTIVE"),
                    (
                        "unplanned_and_active_beyond_critical_boundary",
                        "UNPLANNED_AND_ACTIVE_BEYOND_CRITICAL_BOUNDARY",
                    ),
                ],
                default="other",
                max_length=100,
            ),
        ),
    ]
