# Generated by Django 4.1.3 on 2023-02-25 10:49

from django.db import migrations

from layer_manager.constants import FeatureType


def addAreaToLayerFeatureProperties(apps, schema_editor):
    # get models.
    Feature = apps.get_model("layer_manager", "Feature")
    for feature in Feature.objects.all():
        if feature.type == FeatureType.POLYGON.value and feature.geometry != None:
            polygon = feature.geometry
            # Inplace transformation.
            polygon.transform(3857)
            polygon_area = round(polygon.area, 2)
            feature.properties = {"area": polygon_area}
            feature.save()


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0026_layer_area_category"),
    ]

    operations = [
        migrations.RunPython(addAreaToLayerFeatureProperties),
    ]
