# Generated by Django 4.1.3 on 2023-02-28 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0026_layer_area_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="layer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="layer_manager.layer",
            ),
        ),
    ]
