# Generated by Django 4.1.3 on 2023-02-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0027_add_area_layer_feature"),
        ("layer_manager", "0027_alter_feature_layer"),
    ]

    operations = []
