# Generated by Django 4.1.3 on 2023-03-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0028_merge_20230228_1044"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="layer",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
