# Generated by Django 4.1.3 on 2023-04-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0029_layer_deleted_at_layer_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layer",
            name="index",
        ),
    ]
