# Generated by Django 4.1.3 on 2023-04-20 09:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("layer_manager", "0030_remove_layer_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="geometry",
            field=django.contrib.gis.db.models.fields.GeometryField(dim=3, srid=4326),
        ),
    ]
