# Generated by Django 4.2 on 2023-05-24 04:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0015_imageinfo_alter_fileinfo_id"),
        ("layer_manager", "0031_alter_feature_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="info",
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="FeatureImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="layer_manager.feature",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared.imageinfo",
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="featureimage",
            constraint=models.UniqueConstraint(
                fields=("image", "feature"), name="unique feature image"
            ),
        ),
    ]
