# Generated by Django 4.2 on 2023-06-02 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0032_feature_info_featureimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="featureimage",
            name="feature",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="layer_manager.feature",
            ),
        ),
    ]
