# Generated by Django 4.2 on 2023-06-16 05:49

from django.db import migrations

from ..constants import LayerType


def move_layers_file_to_layer_file_model(apps, schema_editor):
    LayerModel = apps.get_model("layer_manager", "Layer")
    LayerFileModel = apps.get_model("layer_manager", "LayerFile")

    for layer in LayerModel.objects.exclude(
        type__in=[LayerType.CESIUM.value, LayerType.MAPBOX.value]
    ):
        if layer.vector_file:
            LayerFileModel.objects.create(layer=layer, file_info=layer.vector_file)
            layer.vector_file = None

        if layer.vector_tiles:
            LayerFileModel.objects.create(layer=layer, file_info=layer.vector_tiles)
            layer.vector_tiles = None

        if layer.raster_file:
            LayerFileModel.objects.create(layer=layer, file_info=layer.raster_file)
            layer.raster_file = None

        layer.save(update_fields=["vector_file", "vector_tiles", "raster_file"])


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0034_layerfile"),
    ]

    operations = [migrations.RunPython(move_layers_file_to_layer_file_model)]
