# Generated by Django 4.2 on 2023-06-16 06:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0035_move_layers_file_instances_to_LayerFile_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="layer",
            name="raster_file",
        ),
        migrations.RemoveField(
            model_name="layer",
            name="vector_file",
        ),
        migrations.RemoveField(
            model_name="layer",
            name="vector_tiles",
        ),
    ]
