# Generated by Django 4.2 on 2023-07-11 08:04

from django.db import migrations

from shared.constants import FileType

from ..constants import LayerType


def migrate_layer_properties_to_file_info(apps, schema_editor):
    """
    Migrate layer properties of layter type 'contour', 'mbtiles' and 'slope_map' to corresponding 'file_info' objects.
    """
    LayerModel = apps.get_model("layer_manager", "Layer")
    LayerFileModel = apps.get_model("layer_manager", "LayerFile")

    counter = 0
    for layer in LayerModel.objects.filter(
        type__in=[
            LayerType.SLOPE_MAP.value,
            LayerType.CONTOUR.value,
            LayerType.MBTILES.value,
        ],
        properties__isnull=False,
    ):
        layer_properties = layer.properties
        if layer.type == LayerType.CONTOUR.value:
            # Assumption: Only one 'vector_tiles' type FileInfo object exists for
            # one 'contour' type Layer.
            layer_file_object = LayerFileModel.objects.filter(
                layer=layer, file_info__type=FileType.VECTOR_TILES.value
            )

            if not layer_file_object:
                continue

            layer_file_info = layer_file_object.first().file_info

            user_input_layer_properties = {
                "minor_interval": layer_properties.pop("minor_interval"),
                "major_interval": layer_properties.pop("major_interval"),
                "lowest_altitude": layer_properties.pop("lowest_altitude"),
                "highest_altitude": layer_properties.pop("highest_altitude"),
                "threshold_value": layer_properties.pop("threshold_value"),
                "smoothing_filter_size": layer_properties.pop("smoothing_filter_size"),
            }

            layer_file_info.properties = layer_properties
            layer.properties = user_input_layer_properties
        else:
            # Assumption: Only one LayerFile object exists for a 'slope_map' type Layer, and
            # Only one LayerFile object of type 'vector_tiles' exists for one 'mbtiles' type layer.
            layer_file_object = LayerFileModel.objects.filter(
                layer=layer,
                file_info__type__in=[
                    FileType.VECTOR_TILES.value,
                    FileType.SLOPE_MAP.value,
                ],
            )

            if not layer_file_object:
                continue

            layer_file_info = layer_file_object.first().file_info

            layer_file_info.properties = layer_properties
            layer.properties = None

        layer_file_info.save(update_fields=["properties"])
        layer.save(update_fields=["properties"])

        print(
            f"Moving properties of Layer (id={layer.id}) to "
            f"FileInfo(id={layer_file_info.id}) object's properties"
        )

        counter += 1
        print(f"{counter} Layer and FileInfo objects updated.")


class Migration(migrations.Migration):
    dependencies = [
        (
            "layer_manager",
            "0036_remove_layer_raster_file_remove_layer_vector_file_and_more",
        ),
    ]

    operations = [migrations.RunPython(migrate_layer_properties_to_file_info)]
