# Generated by Django 4.2.4 on 2023-08-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "layer_manager",
            "0036_remove_layer_raster_file_remove_layer_vector_file_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="attributes",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="feature",
            name="info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
