# Generated by Django 4.2 on 2023-08-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0037_move_layer_properties_to_file_info_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="layerfile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="layerfile",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
