# Generated by Django 4.2.4 on 2023-08-27 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0037_remove_feature_name_feature_attributes_and_more"),
        ("layer_manager", "0038_layerfile_deleted_at_layerfile_is_deleted"),
    ]

    operations = []
