# Generated by Django 4.2.4 on 2023-08-29 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0020_set_is_deleted_for_deleted_files"),
        ("layer_manager", "0039_merge_20230827_1145"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="featureimage",
            options={"ordering": ("-created_at",)},
        ),
        migrations.RemoveConstraint(
            model_name="featureimage",
            name="unique feature image",
        ),
        migrations.AlterField(
            model_name="featureimage",
            name="image",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="shared.imageinfo"
            ),
        ),
        migrations.AlterField(
            model_name="layerfile",
            name="layer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="layer_files",
                to="layer_manager.layer",
            ),
        ),
    ]
