# Generated by Django 4.2 on 2023-08-09 08:59
from django.db import migrations

SQL_QUERY = """
CREATE OR REPLACE FUNCTION get_tile(target_layer_id UUID, zoom_level INT, tile_x INT, tile_y INT)
RETURNS TABLE (tile bytea) AS $$
DECLARE
  bounds geometry;
BEGIN
  RETURN QUERY
  -- Convert ZXY coordinates to bounding box coordinates.
  WITH bounds AS (
    SELECT ST_TileEnvelope(zoom_level, tile_x, tile_y) AS geom,
           ST_TileEnvelope(zoom_level, tile_x, tile_y)::box2d AS b2d
  ),

  -- Transform and filter geometries that intersect with the bounding box.
  mvtgeom AS (
    -- TODO: Remove ST_Force2D when this issue get fixed in GEOS. See https://trac.osgeo.org/postgis/ticket/4690

    -- Add attributes with geometry.
    SELECT ST_AsMVTGeom(ST_Transform(ST_Force2D(feature_table.geometry), 3857), bounds.b2d) AS geom, feature_table.id, feature_table.type, feature_table.properties->>'text' as textbox_text
    FROM layer_manager_feature feature_table, bounds
    WHERE ST_Intersects(feature_table.geometry, ST_Transform(bounds.geom, 4326)) AND feature_table.layer_id = target_layer_id
  )

  -- Generate Mapbox Vector Tiles (MVT) from the filtered geometries.
  SELECT ST_AsMVT(mvtgeom.*) FROM mvtgeom;
END;
$$ LANGUAGE plpgsql;
"""

REVERSE_SQL = "DROP FUNCTION IF EXISTS get_tile(UUID, INT, INT, INT);"


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0040_alter_featureimage_options_and_more"),
    ]

    operations = [
        migrations.RunSQL(sql=SQL_QUERY, reverse_sql=REVERSE_SQL),
    ]
