# Generated by Django 4.2.4 on 2023-09-04 09:08

from django.db import migrations

SQL_QUERY = """
CREATE TYPE feature_type AS (
    id uuid,
    geometry geometry
);

CREATE OR REPLACE FUNCTION bulk_update_features(features feature_type[])
RETURNS VOID AS $$
BEGIN
    -- Create (or replace if already exists) the temporary table
    CREATE TEMP TABLE IF NOT EXISTS temp_feature_updates (
        id uuid,
        geometry geometry
    ) ON COMMIT DELETE ROWS;

    -- Truncate temporary table to ensure it's empty
    TRUNCATE temp_feature_updates;

    -- Insert data into the temporary table using UNNEST
    INSERT INTO temp_feature_updates (id, geometry)
    SELECT id, geometry
    FROM UNNEST(features) AS t(id, geometry);

    UPDATE layer_manager_feature
    SET geometry = temp_feature_updates.geometry
	FROM temp_feature_updates
    WHERE layer_manager_feature.id = temp_feature_updates.id;

    -- No need to clean up, temporary table rows will be automatically deleted at the end of the transaction

END;
$$ LANGUAGE plpgsql;
"""

REVERSE_SQL = "DROP FUNCTION IF EXISTS bulk_update_features(features feature_type[]);"


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0042_remove_layer_styles"),
    ]

    operations = [
        migrations.RunSQL(sql=SQL_QUERY, reverse_sql=REVERSE_SQL),
    ]
