# Generated by Django 4.2.4 on 2023-09-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0043_bulk_update_features_function"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="clamped_status",
            field=models.CharField(
                choices=[
                    ("not_clamped", "NOT_CLAMPED"),
                    ("already_clamped", "ALREADY_CLAMPED"),
                    ("started", "STARTED"),
                    ("processing", "PROCESSING"),
                    ("done", "DONE"),
                    ("failed", "FAILED"),
                ],
                default="not_clamped",
                max_length=50,
            ),
        ),
    ]
