# Generated by Django 4.2.4 on 2023-10-16 09:50

from django.db import migrations

SQL_QUERY = """
CREATE OR REPLACE FUNCTION get_features_by_layer(layer uuid)
RETURNS json AS
$$
DECLARE
    features_json json;
BEGIN
   SELECT json_agg(row_to_json(features))
   INTO features_json
   FROM (SELECT id,ST_ASTEXT(geometry) as geometry FROM layer_manager_feature WHERE layer_id = layer) AS features;
   RETURN features_json;
END;
$$ LANGUAGE plpgsql;
"""

REVERSE_SQL = "DROP FUNCTION IF EXISTS get_features_by_layer(layer uuid);"


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0044_layer_clamped_status"),
    ]

    operations = [migrations.RunSQL(sql=SQL_QUERY, reverse_sql=REVERSE_SQL)]
