# Generated by Django 4.2.4 on 2024-10-04 08:45

import json

from django.db import migrations

from assets.assets_path import AssetPath
from layer_manager.constants import LayerType


def refactor_layer_features_styles(apps, schema_editor):
    """
    Update the Layer's features_styles according to the new features_styles.json.
    """

    LayerModel = apps.get_model("layer_manager", "Layer")

    for layer in LayerModel.objects.filter(type=LayerType.VECTOR.value).all():
        if layer.features_styles:
            features_styles_dict = (
                layer.features_styles
                if isinstance(layer.features_styles, dict)
                else json.loads(layer.features_styles)
            )

            if features_styles_dict:
                features_styles_dict["line"]["strokeThickness"] = float(
                    features_styles_dict["line"]["strokeThickness"]
                )
                features_styles_dict["polygon"]["strokeThickness"] = float(
                    features_styles_dict["polygon"]["strokeThickness"]
                )

                # 0.2 was the default value for this property which was handled statically in frontend
                # So making it 0.2 for previous undefined fillOpacity property for backward compatibility.
                features_styles_dict["polygon"]["fillOpacity"] = 0.2

                # Add textbox styles if not present.
                if features_styles_dict.get("textbox"):
                    features_styles_dict["textbox"]["fontSize"] = int(
                        features_styles_dict["textbox"]["fontSize"]
                    )
                else:
                    features_styles_dict["textbox"] = {
                        "fontColor": "#000000",
                        "fontSize": 16,
                        "backgroundColor": "#FFCC33",
                    }
                layer.features_styles = features_styles_dict
        else:
            with open(AssetPath.FEATURES_STYLE.value, "r") as features_style:
                layer.features_styles = json.load(features_style)

        layer.save()


def reverse_refactor_layer_features_styles(apps, schema_editor):

    LayerModel = apps.get_model("layer_manager", "Layer")

    for layer in LayerModel.objects.filter(type="vector").all():
        if layer.features_styles:
            features_styles_dict = (
                layer.features_styles
                if isinstance(layer.features_styles, dict)
                else json.loads(layer.features_styles)
            )

            if features_styles_dict:
                features_styles_dict["line"]["strokeThickness"] = str(
                    features_styles_dict["line"]["strokeThickness"]
                )
                features_styles_dict["polygon"]["strokeThickness"] = str(
                    features_styles_dict["polygon"]["strokeThickness"]
                )
                features_styles_dict["polygon"].pop("fillOpacity", None)
                features_styles_dict["textbox"]["fontSize"] = str(
                    features_styles_dict["textbox"]["fontSize"]
                )


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0045_get_features_by_layer_function"),
    ]

    operations = [
        migrations.RunPython(
            code=refactor_layer_features_styles,
            reverse_code=reverse_refactor_layer_features_styles,
        )
    ]
