# Generated by Django 4.2.4 on 2024-10-18 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0046_refactor_layer_features_styles_20241004_0845"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="layer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="features",
                to="layer_manager.layer",
            ),
        ),
    ]
