# Generated by Django 4.2.4 on 2024-12-24 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("layer_manager", "0048_update_get_tile_function"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feature",
            options={},
        ),
    ]
