# Generated by Django 3.2.6 on 2022-04-18 13:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("site_manager", "0001_initial"),
        ("shared", "0002_alter_fileinfo_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Iteration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("gsd", models.FloatField(blank=True, null=True)),
                (
                    "captured_dsm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shared.fileinfo",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="site_manager.site",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
