# Generated by Django 3.2.6 on 2022-04-18 08:50

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iteration_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeapBoundary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("volume", models.FloatField(null=True)),
                ("status", models.SmallIntegerField(null=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
                ("remarks", models.CharField(max_length=200, null=True)),
                ("centroid", models.CharField(max_length=50, null=True)),
                ("bulk_density", models.FloatField(null=True)),
                ("weight", models.FloatField(null=True)),
                (
                    "iteration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iteration_manager.iteration",
                    ),
                ),
            ],
        ),
    ]
