# Generated by Django 3.2.6 on 2022-07-05 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_manager", "0008_auto_20220503_1218"),
        ("shared", "0004_auto_20220705_0737"),
        ("iteration_manager", "0003_auto_20220503_1218"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iteration",
            options={"ordering": ["date"]},
        ),
        migrations.AddField(
            model_name="iteration",
            name="orthomosaic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="ortho_iteration",
                to="shared.fileinfo",
            ),
        ),
        migrations.AddField(
            model_name="iteration",
            name="orthomosaic_cog",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shared.batchjob",
            ),
        ),
        migrations.AlterField(
            model_name="iteration",
            name="captured_dsm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shared.fileinfo",
            ),
        ),
        migrations.AlterField(
            model_name="iteration",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="site_manager.site",
            ),
        ),
    ]
