# Generated by Django 3.2.6 on 2022-07-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iteration_manager", "0004_auto_20220705_0737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heapboundary",
            name="volume",
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name="heapboundary",
            name="weight",
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
    ]
