# Generated by Django 3.2.6 on 2022-07-11 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0005_alter_batchjob_env_variables"),
        ("iteration_manager", "0005_auto_20220711_0729"),
    ]

    operations = [
        migrations.AddField(
            model_name="iteration",
            name="terrain_tiles",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="terrain_iteration",
                to="shared.batchjob",
            ),
        ),
    ]
