# Generated by Django 3.2.6 on 2022-09-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iteration_manager", "0006_iteration_terrain_tiles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="heapboundary",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="iteration",
            options={"ordering": ("-date",)},
        ),
    ]
