# Generated by Django 4.1.3 on 2022-11-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iteration_manager", "0007_auto_20220920_0812"),
    ]

    operations = [
        migrations.RenameField(
            model_name="heapboundary",
            old_name="volume",
            new_name="cut_volume",
        ),
        migrations.RenameField(
            model_name="heapboundary",
            old_name="weight",
            new_name="cut_weight",
        ),
        migrations.RemoveField(
            model_name="heapboundary",
            name="status",
        ),
        migrations.AddField(
            model_name="heapboundary",
            name="fill_volume",
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name="heapboundary",
            name="fill_weight",
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name="heapboundary",
            name="net_volume",
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name="heapboundary",
            name="net_weight",
            field=models.DecimalField(decimal_places=4, max_digits=19, null=True),
        ),
    ]
