# Generated by Django 4.1.3 on 2023-01-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iteration_manager", "0009_iteration_terrain_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iteration",
            name="gsd",
        ),
        migrations.AddField(
            model_name="heapboundary",
            name="base_iteration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="iteration_manager.iteration",
            ),
        ),
        migrations.AddField(
            model_name="heapboundary",
            name="base_reference",
            field=models.CharField(
                choices=[
                    ("visible_ground", "VisibleGround"),
                    ("site_base_dsm", "SiteBaseDsm"),
                    ("other_iteration_dsm", "OtherIterationDsm"),
                ],
                default="visible_ground",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="heapboundary",
            name="iteration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="heaps",
                to="iteration_manager.iteration",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="heapboundary",
            unique_together={("iteration", "base_iteration")},
        ),
    ]
