# Generated by Django 4.1.3 on 2023-01-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "iteration_manager",
            "0010_remove_iteration_gsd_heapboundary_base_iteration_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="heapboundary",
            unique_together=set(),
        ),
    ]
