# Generated by Django 4.1.3 on 2023-02-03 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0012_rename_filename_fileinfo_name_and_more"),
        ("iteration_manager", "0011_alter_heapboundary_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iteration",
            name="captured_dsm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="captured_dsm_iteration",
                to="shared.fileinfo",
            ),
        ),
    ]
