# Generated by Django 4.1.3 on 2023-02-08 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0013_alter_fileinfo_type"),
        ("iteration_manager", "0012_alter_iteration_captured_dsm"),
    ]

    operations = [
        migrations.AddField(
            model_name="iteration",
            name="captured_dsm_cog",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="captured_dsm_cog_iteration",
                to="shared.fileinfo",
            ),
        ),
    ]
