# Generated by Django 4.1.3 on 2023-02-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iteration_manager", "0012_alter_iteration_captured_dsm"),
    ]

    operations = [
        migrations.AddField(
            model_name="heapboundary",
            name="included_in_kpi",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="heapboundary",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("other", "Other"),
                    ("overburden", "Overburden"),
                    ("ore", "Ore"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
