# Generated by Django 4.1.3 on 2023-02-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iteration_manager", "0013_heapboundary_include_in_kpi_and_more"),
        ("iteration_manager", "0013_iteration_captured_dsm_cog"),
    ]

    operations = []
