# Generated by Django 4.1.3 on 2023-02-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iteration_manager", "0014_merge_20230213_1202"),
    ]

    operations = [
        migrations.AddField(
            model_name="heapboundary",
            name="category",
            field=models.CharField(
                choices=[
                    ("incremental_dump_volume", "INCREMENTAL_DUMP_VOLUME"),
                    ("excavated_volume", "EXCAVATED_VOLUME"),
                    ("stock_volume", "STOCK_VOLUME"),
                    ("other", "OTHER"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
