# Generated by Django 4.2 on 2023-05-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iteration_manager", "0015_heapboundary_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="iteration",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="iteration",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
