# Generated by Django 4.2 on 2023-05-29 07:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iteration_manager", "0016_iteration_deleted_at_iteration_is_deleted"),
    ]

    operations = [
        # Ref: https://stackoverflow.com/a/49160040.
        migrations.RunSQL(
            "ALTER TABLE iteration_manager_heapboundary ALTER COLUMN geometry type geometry(MultiPolygon, 4326) using ST_Multi(geometry);",
            state_operations=[
                migrations.AlterField(
                    model_name="heapboundary",
                    name="geometry",
                    field=django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326
                    ),
                ),
            ],
        ),
    ]
