# Generated by Django 4.2 on 2023-07-04 06:45

from django.db import migrations

from layer_manager.constants import LayerType
from rainbow.env_variables import EnvVariable
from shared.constants import FileStatus, FileType

FILE_STATUS_BY_BATCH_JOB_STATUS = {
    "started": FileStatus.STARTED.value,
    "processing": FileStatus.PROCESSING.value,
    "completed": FileStatus.DONE.value,
    "failed": FileStatus.FAILED.value,
}


def get_env_variable(env_variables_list: list, name: str) -> dict:
    for env_variable in env_variables_list:
        if env_variable["name"] == name:
            return env_variable.get("value")


def move_ortho_to_layer(apps, schema_editor):
    IterationModel = apps.get_model("iteration_manager", "Iteration")
    LayerModel = apps.get_model("layer_manager", "Layer")
    LayerFileModel = apps.get_model("layer_manager", "LayerFile")
    FileInfoModel = apps.get_model("shared", "FileInfo")

    for iteration in IterationModel.objects.filter(orthomosaic__isnull=False):
        print(f"Creating ortho layer for iteration: {iteration.id}")

        layer = LayerModel.objects.create(
            name=f"Orthomosaic - {iteration.date.strftime('%d-%m-%Y')}",
            iteration=iteration,
            site=iteration.site,
            type=LayerType.ORTHOMOSAIC.value,
        )

        # Add ortho file info to layer files.
        LayerFileModel.objects.create(layer=layer, file_info=iteration.orthomosaic)
        iteration.orthomosaic = None

        # Adding ortho cog to layer files.
        if ortho_cog := iteration.orthomosaic_cog:
            # Convert ortho cog BatchJob instance to FileInfo.
            s3_key_with_bucket_name = get_env_variable(
                ortho_cog.env_variables, "OUTPUT_S3_KEY"
            )
            s3_key = s3_key_with_bucket_name.replace(
                f"{EnvVariable.BUCKET_NAME.value}/", ""
            )
            ortho_cog_file_info = FileInfoModel.objects.create(
                name=f"{iteration.name}-ortho-cog.tif",
                type=FileType.ORTHOMOSAIC_COG.value,
                s3_key=s3_key,
                status=FILE_STATUS_BY_BATCH_JOB_STATUS[ortho_cog.status],
                batch_job=ortho_cog,
                org=iteration.site.project.org,
            )
            print("Adding ortho cog file to the layer")
            LayerFileModel.objects.create(layer=layer, file_info=ortho_cog_file_info)
            iteration.orthomosaic_cog = None

        iteration.save(update_fields=["orthomosaic", "orthomosaic_cog"])


class Migration(migrations.Migration):
    dependencies = [
        ("iteration_manager", "0017_alter_heapboundary_geometry"),
        (
            "layer_manager",
            "0036_remove_layer_raster_file_remove_layer_vector_file_and_more",
        ),
        ("shared", "0017_auto_20230705_1227"),
    ]

    operations = [migrations.RunPython(move_ortho_to_layer)]
