# Generated by Django 4.2.4 on 2023-08-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iteration_manager", "0017_alter_heapboundary_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="iteration",
            name="info",
            field=models.TextField(null=True, blank=True),
        ),
    ]
