# Generated by Django 4.2 on 2023-07-04 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iteration_manager", "0018_move_ortho_to_layer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iteration",
            name="orthomosaic",
        ),
        migrations.RemoveField(
            model_name="iteration",
            name="orthomosaic_cog",
        ),
    ]
