# Generated by Django 4.2.4 on 2023-08-27 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iteration_manager", "0018_iteration_info"),
        ("iteration_manager", "0019_remove_iteration_orthomosaic_and_more"),
    ]

    operations = []
