# Generated by Django 4.2.4 on 2024-05-27 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iteration_manager", "0020_merge_20230827_1145"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="iteration",
            options={"ordering": ("-created_at",)},
        ),
    ]
