# Generated by Django 4.2.4 on 2024-10-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iteration_manager", "0021_alter_iteration_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="iteration",
            name="serial_id",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
