# Generated by Django 4.2.4 on 2024-10-17 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iteration_manager", "0022_iteration_serial_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iteration",
            name="serial_id",
        ),
    ]
