# Generated by Django 3.2.6 on 2022-04-26 10:10

from django.db import migrations


def create_default_projects(apps, schema_editor):
    Organisation = apps.get_model("org_manager", "Organisation")
    Project = apps.get_model("project_manager", "Project")
    for org in Organisation.objects.all():
        Project.objects.create(name="Project 1", org=org)


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_default_projects)]
