# Generated by Django 3.2.6 on 2022-04-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0002_create_default_project_for_each_org"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["created_at"]},
        ),
    ]
