# Generated by Django 3.2.6 on 2022-07-29 06:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_manager", "0006_alter_usergroup_users"),
        ("project_manager", "0003_alter_project_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("can_view", models.BooleanField()),
                ("can_manage_sites", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="project_manager.project",
                    ),
                ),
                (
                    "user_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_manager.usergroup",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("project", "user_group")},
            },
        ),
    ]
