# Generated by Django 3.2.6 on 2022-09-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project_manager", "0004_projectpermission"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterModelOptions(
            name="projectpermission",
            options={"ordering": ("-created_at",)},
        ),
    ]
