# Generated by Django 3.2.6 on 2022-05-03 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisation",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="organisation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organisation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
