# Generated by Django 3.2.6 on 2022-08-26 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0005_alter_batchjob_env_variables"),
        ("org_manager", "0002_auto_20220503_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="logo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shared.fileinfo",
            ),
        ),
    ]
