# Generated by Django 3.2.6 on 2022-09-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("org_manager", "0003_organisation_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisation",
            options={"ordering": ("-created_at",)},
        ),
    ]
