# Generated by Django 4.1.2 on 2022-10-19 07:35

from django.db import migrations, models

import org_manager.feature_flags


class Migration(migrations.Migration):
    dependencies = [
        ("org_manager", "0004_alter_organisation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="features",
            field=models.JSONField(
                default=org_manager.feature_flags.FeatureFlag.get_default_values
            ),
        ),
    ]
