# Generated by Django 4.1.2 on 2022-12-07 07:32

import json

from django.db import migrations

"""
References: https://stackoverflow.com/questions/49387552/django-postgres-make-custom-migration-from-charfield-to-jsonfield
            https://stackoverflow.com/questions/11174024/attributeerrorstr-object-has-no-attribute-read
"""


def add_mbtiles_in_features_json(apps, schema_editor):
    OrgModel = apps.get_model("org_manager", "Organisation")
    for org in OrgModel.objects.all():
        try:
            prev_json = (
                org.features
                if isinstance(org.features, dict)
                else json.loads(org.features)
            )
            updated_json = json.dumps({"mbtiles": True, **prev_json})
            org.features = updated_json
            org.save()
        except json.decoder.JSONDecodeError as e:
            print("Cannot convert {} object".format(org.pk))


class Migration(migrations.Migration):

    dependencies = [
        ("org_manager", "0005_organisation_features"),
    ]

    operations = [
        migrations.RunPython(add_mbtiles_in_features_json),
    ]
