# Generated by Django 4.1.3 on 2023-03-21 09:30
import json

from django.db import migrations


def add_slope_map_in_features_json(apps, schema_editor):
    OrgModel = apps.get_model("org_manager", "Organisation")
    for org in OrgModel.objects.all():
        try:
            prev_json = (
                org.features
                if isinstance(org.features, dict)
                else json.loads(org.features)
            )
            updated_json = json.dumps({"slope_map": True, **prev_json})
            org.features = updated_json
            org.save()
        except json.decoder.JSONDecodeError as e:
            print("Cannot convert {} object".format(org.pk))


class Migration(migrations.Migration):
    dependencies = [
        ("org_manager", "0006_auto_20221207_0732"),
    ]

    operations = [
        migrations.RunPython(add_slope_map_in_features_json),
    ]
