# Generated by Django 4.1.3 on 2023-03-23 10:45

import uuid

import django.db.models.deletion
from django.db import migrations, models

import shared.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("org_manager", "0007_auto_20230321_0930"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationAccessToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.CharField(
                        default=shared.helpers.generate_token_string,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "org",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_token",
                        to="org_manager.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
