# Generated by Django 4.2 on 2023-07-14 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("org_manager", "0008_organisationaccesstoken"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organisation",
            old_name="features",
            new_name="feature_flags",
        ),
    ]
